type CopyEntry = readonly [zhCN: string, enUS: string];

// 页面以现有中文作为稳定键。第一项是优化后的中文，第二项是对应英文。
// 未登记的内容保持原文，动态的文件名、用户名和服务端消息不会被改写。
const copy: Record<string, CopyEntry> = {
  中文: ['中文', '中文'],
  文件: ['文件', 'Files'],
  文件夹: ['文件夹', 'Folder'],
  分享: ['分享', 'Shares'],
  直链: ['直链', 'Direct links'],
  用户: ['用户', 'User'],
  用户组: ['用户组', 'User group'],
  系统: ['系统', 'System'],
  名称: ['名称', 'Name'],
  大小: ['大小', 'Size'],
  类型: ['类型', 'Type'],
  状态: ['状态', 'Status'],
  时间: ['时间', 'Time'],
  操作: ['操作', 'Actions'],
  操作者: ['操作者', 'Actor'],
  对象: ['对象', 'Target'],
  格式: ['格式', 'Format'],
  说明: ['说明', 'Description'],
  密码: ['密码', 'Password'],
  '密码：': ['密码：', 'Password: '],
  有效期: ['有效期', 'Expiration'],
  有效期至: ['有效期至', 'Expires'],
  创建时间: ['创建时间', 'Created'],
  更新时间: ['更新时间', 'Updated'],
  提交时间: ['提交时间', 'Submitted'],
  生成时间: ['生成时间', 'Generated'],
  来源IP: ['来源 IP', 'Source IP'],
  '来源 IP': ['来源 IP', 'Source IP'],
  保存: ['保存', 'Save'],
  保存配置: ['保存', 'Save'],
  取消: ['取消', 'Cancel'],
  完成: ['完成', 'Done'],
  创建: ['创建', 'Create'],
  生成: ['生成', 'Generate'],
  新增: ['新增', 'Add'],
  编辑: ['编辑', 'Edit'],
  配置: ['配置', 'Configure'],
  删除: ['删除', 'Delete'],
  删除消息: ['删除消息', 'Delete message'],
  启用: ['启用', 'Enable'],
  禁用: ['禁用', 'Disable'],
  作废: ['作废', 'Revoke'],
  通过: ['通过', 'Approve'],
  驳回: ['驳回', 'Reject'],
  预览: ['预览', 'Preview'],
  下载: ['下载', 'Download'],
  上传: ['上传', 'Upload'],
  复制: ['复制', 'Copy'],
  打开: ['打开', 'Open'],
  刷新数据: ['刷新', 'Refresh'],
  返回首页: ['返回首页', 'Back to home'],
  返回登录: ['返回登录', 'Back to login'],
  重新下载: ['重新下载', 'Download again'],
  正在检查直链状态: ['正在检查直链状态…', 'Checking direct link…'],
  无法打开直链: ['无法打开直链', 'Direct link unavailable'],
  直链不存在或无法访问: [
    '直链不存在或无法访问',
    'This direct link does not exist or is unavailable',
  ],
  直链已过期: ['直链已过期', 'Direct link expired'],
  直链已被封禁: ['直链已被封禁', 'Direct link blocked'],
  该直链已过期: ['该直链已过期', 'This direct link has expired'],
  该直链已被管理员封禁: [
    '该直链已被管理员封禁',
    'This direct link was blocked by an administrator',
  ],
  上传或替换: ['上传图标', 'Upload icon'],
  恢复默认: ['恢复默认', 'Restore default'],
  新建文件夹: ['新建文件夹', 'New folder'],
  新增方案: ['新增方案', 'Add plan'],
  新增用户组: ['新增用户组', 'Add user group'],
  重设密码: ['重设密码', 'Reset password'],
  重命名: ['重命名', 'Rename'],
  生成分享: ['生成分享', 'Create share'],
  生成直链: ['生成直链', 'Create direct link'],
  配置分享: ['配置分享', 'Configure share'],
  配置直链: ['配置直链', 'Configure direct link'],
  配置权限: ['配置权限', 'Configure permissions'],
  生成邀请码: ['生成邀请码', 'Generate codes'],
  发放邀请码: ['发放邀请码', 'Issue invitation codes'],
  确认驳回: ['确认驳回', 'Reject'],
  全部已读: ['全部已读', 'Mark all as read'],
  清空: ['清空', 'Clear'],
  切换语言: ['切换语言', 'Change language'],
  打开消息中心: ['打开消息中心', 'Open messages'],
  打开导航菜单: ['打开导航菜单', 'Open navigation'],
  关闭导航菜单: ['关闭导航菜单', 'Close navigation'],
  展开导航菜单: ['展开导航菜单', 'Expand navigation'],
  收起导航菜单: ['收起导航菜单', 'Collapse navigation'],
  站点图标: ['站点图标', 'Site icon'],
  当前站点图标: ['当前站点图标', 'Current site icon'],
  全部文件: ['全部文件', 'All files'],
  文件总数: ['文件总数', 'Files'],
  用户总数: ['用户总数', 'Users'],
  有效分享: ['有效分享', 'Active shares'],
  有效直链: ['有效直链', 'Active direct links'],
  服务状态: ['服务状态', 'Service status'],
  分享消耗: ['分享用量', 'Share usage'],
  累计下载: ['累计下载', 'Total downloads'],
  累计流量: ['累计流量', 'Total traffic'],
  API服务: ['API 服务', 'API service'],
  'API 服务': ['API 服务', 'API service'],
  数据库连接: ['数据库连接', 'Database'],
  文件存储: ['文件存储', 'File storage'],
  正常: ['正常', 'Operational'],
  响应正常: ['运行正常', 'Operational'],
  更新于: ['更新于', 'Updated at'],
  已用: ['已用', 'Used'],
  '/ 可用': ['/ 可用', '/ available'],
  文件分享: ['文件分享', 'Shared files'],
  文件下载: ['文件下载', 'File download'],
  文件预览: ['文件预览', 'File preview'],
  当前资源: ['当前资源', 'Selected item'],
  分享内容: ['分享内容', 'Shared content'],
  直链内容: ['直链内容', 'Linked file'],
  分享链接: ['分享链接', 'Share link'],
  直链地址: ['直链地址', 'Direct link'],
  访问密码: ['访问密码', 'Access password'],
  自定义密码: ['自定义密码', 'Custom password'],
  说明格式: ['说明格式', 'Description format'],
  分享页说明: ['分享说明', 'Share description'],
  分享说明: ['分享说明', 'Share description'],
  分享说明预览: ['分享说明预览', 'Description preview'],
  下载次数: ['下载次数', 'Downloads'],
  下载次数限制: ['下载次数限制', 'Download limit'],
  下载流量: ['下载流量', 'Traffic'],
  下载流量限制: ['下载流量限制', 'Traffic limit'],
  无密码: ['无密码', 'No password'],
  不限: ['不限', 'Unlimited'],
  不限制: ['不限', 'Unlimited'],
  永久: ['永久', 'Never'],
  永久有效: ['永久有效', 'Never expires'],
  长期有效: ['长期有效', 'No expiration'],
  '1 天': ['1 天', '1 day'],
  '7 天': ['7 天', '7 days'],
  '30 天': ['30 天', '30 days'],
  从现在起1天: ['1 天', '1 day from now'],
  '从现在起 1 天': ['1 天', '1 day from now'],
  '从现在起 7 天': ['7 天', '7 days from now'],
  '从现在起 30 天': ['30 天', '30 days from now'],
  保持当前有效期: ['保持当前有效期', 'Keep current expiration'],
  保持当前: ['保持当前', 'Keep current'],
  重新随机: ['重新生成', 'Generate new'],
  随机: ['随机生成', 'Random'],
  自定义: ['自定义', 'Custom'],
  由: ['由', 'Shared by'],
  到期: ['到期', 'expires'],
  已下载: ['已下载', 'Downloaded'],
  已用流量: ['已用流量', 'Traffic used'],
  正在准备下载: ['正在准备下载', 'Preparing download'],
  空文件夹: ['文件夹为空', 'This folder is empty'],
  文件审查: ['文件审查', 'File review'],
  分享审查: ['分享审查', 'Share review'],
  系统审计: ['系统审计', 'System audit'],
  待审核: ['待审核', 'Pending'],
  已通过: ['已通过', 'Approved'],
  已驳回: ['已驳回', 'Rejected'],
  已停用: ['已停用', 'Disabled'],
  已过期: ['已过期', 'Expired'],
  生效中: ['生效中', 'Active'],
  已禁用: ['已禁用', 'Disabled'],
  可使用: ['可使用', 'Available'],
  已使用: ['已使用', 'Used'],
  已作废: ['已作废', 'Revoked'],
  系统超级管理员: ['系统超级管理员', 'Super administrator'],
  所属用户组: ['所属用户组', 'User groups'],
  用户组名称: ['用户组名称', 'Group name'],
  配额方案: ['配额方案', 'Quota plans'],
  用户组配额: ['用户组配额', 'Group quotas'],
  权限配置: ['权限配置', 'Permissions'],
  已授予权限: ['已授予权限', 'Granted permissions'],
  未授予权限: ['未授予权限', 'No permissions granted'],
  存储空间: ['存储空间', 'Storage'],
  单文件: ['单文件', 'Per file'],
  单文件大小: ['单文件大小', 'File size'],
  每日上传: ['每日上传', 'Daily upload'],
  每日上传流量: ['每日上传流量', 'Daily upload traffic'],
  每日上传次数: ['每日上传次数', 'Daily uploads'],
  每日次数: ['每日次数', 'Daily count'],
  '分享 / 直链': ['分享 / 直链', 'Shares / direct links'],
  优先级: ['优先级', 'Priority'],
  注册策略: ['注册策略', 'Registration'],
  注册需要邀请码: ['注册需要邀请码', 'Require an invitation code'],
  邀请码: ['邀请码', 'Invitation code'],
  发放对象: ['发放对象', 'Recipient'],
  发放给用户: ['发放给用户', 'Send to user'],
  发放给用户组: ['发放给用户组', 'Send to user group'],
  使用人: ['使用人', 'Used by'],
  方案名称: ['方案名称', 'Plan name'],
  方案用途: ['方案用途', 'Purpose'],
  位数: ['位数', 'Length'],
  区分大小写: ['区分大小写', 'Case-sensitive'],
  包含字母: ['包含字母', 'Include letters'],
  包含数字: ['包含数字', 'Include numbers'],
  内容审核: ['内容审核', 'Content review'],
  上传文件需要先审核: ['上传文件需要审核', 'Review uploaded files'],
  自定义分享说明需要先审核: [
    '自定义分享说明需要审核',
    'Review custom share descriptions',
  ],
  下载策略: ['下载策略', 'Download settings'],
  文件夹打包位置: ['文件夹打包方式', 'Folder packaging'],
  分享页文件交付: ['分享下载方式', 'Share delivery'],
  后端校验并打包ZIP: ['后端打包 ZIP', 'Package ZIP on the server'],
  '后端校验并打包 ZIP': ['后端打包 ZIP', 'Package ZIP on the server'],
  前端逐文件打包: ['前端打包 ZIP', 'Package ZIP in the browser'],
  前端读取Blob流: ['浏览器接收文件流', 'Receive as a browser blob'],
  '前端读取 Blob 流': ['浏览器接收文件流', 'Receive as a browser blob'],
  一次性临时链接: ['临时下载链接', 'Temporary download link'],
  站点信息: ['站点信息', 'Site'],
  站点名称: ['站点名称', 'Site name'],
  存储路径: ['存储路径', 'Storage path'],
  随机码: ['随机码', 'Random codes'],
  分享码: ['分享码', 'Share codes'],

  '管理你的文件和文件夹。': ['查看和管理文件。', 'View and manage files.'],
  '查看你已经生成的文件和文件夹分享。': [
    '查看已生成的分享。',
    'View generated shares.',
  ],
  '查看你已经生成的下载直链及使用情况。': [
    '查看已生成的直链和使用量。',
    'View direct links and usage.',
  ],
  '掌握站点资源分享和服务运行状态。': [
    '查看站点资源和服务状态。',
    'View site resources and service status.',
  ],
  '掌握站点资源、分享和服务运行状态。': [
    '查看站点资源和服务状态。',
    'View site resources and service status.',
  ],
  '管理站点账户用户组归属登录状态和密码。': [
    '管理账户、用户组和登录状态。',
    'Manage accounts, groups, and sign-in status.',
  ],
  '管理站点账户、用户组归属、登录状态和密码。': [
    '管理账户、用户组和登录状态。',
    'Manage accounts, groups, and sign-in status.',
  ],
  '权限和配额均直接配置到用户组用户只继承所属用户组的设置。': [
    '权限和配额由用户组决定。',
    'Permissions and quotas are assigned through user groups.',
  ],
  '权限和配额均直接配置到用户组，用户只继承所属用户组的设置。': [
    '权限和配额由用户组决定。',
    'Permissions and quotas are assigned through user groups.',
  ],
  '审查待发布内容并追踪关键管理操作。': [
    '审查内容并查看系统操作记录。',
    'Review content and view system activity.',
  ],
  '审查待发布内容，并追踪关键管理操作。': [
    '审查内容并查看系统操作记录。',
    'Review content and view system activity.',
  ],
  '调整站点基础信息存储位置和全局下载行为。': [
    '配置站点、存储和下载方式。',
    'Configure the site, storage, and downloads.',
  ],
  '调整站点基础信息、存储位置和全局下载行为。': [
    '配置站点、存储和下载方式。',
    'Configure the site, storage, and downloads.',
  ],
  '用于页面标题和产品标识。': [
    '显示在页面标题和站点标识中。',
    'Shown in the page title and site identity.',
  ],
  '必须填写服务器上的绝对路径。': [
    '填写服务器绝对路径。',
    'Enter an absolute server path.',
  ],
  '保存后仅影响新生成的邀请码和随机分享码已有内容保持不变。': [
    '配置仅用于新生成的随机码。',
    'Changes apply only to newly generated codes.',
  ],
  '保存后仅影响新生成的邀请码和随机分享码，已有内容保持不变。': [
    '配置仅用于新生成的随机码。',
    'Changes apply only to newly generated codes.',
  ],
  '仅影响保存配置后新上传的文件和新提交的自定义分享说明。': [
    '配置仅用于之后提交的内容。',
    'Changes apply only to content submitted afterward.',
  ],
  '前端打包适合小型目录，后端打包对大目录更稳定；临时链接可交给浏览器直接下载。':
    [
      '选择文件夹打包和分享下载的处理位置。',
      'Choose where folder packaging and share downloads are handled.',
    ],
  '修改文件存储路径后，新上传和后续下载会立即使用新目录，请确认运行账户拥有读写权限。':
    [
      '修改后，新上传和下载会使用新路径。运行账户必须具有读写权限。',
      'New uploads and downloads use the new path. The service account needs read and write access.',
    ],
  '空值表示不限0表示禁止使用对应资源。': [
    '留空表示不限，0 表示禁用。',
    'Leave blank for unlimited. Enter 0 to disable.',
  ],
  '空值表示不限，0 表示禁止使用对应资源。': [
    '留空表示不限，0 表示禁用。',
    'Leave blank for unlimited. Enter 0 to disable.',
  ],
  '用户属于多个用户组时采用优先级最高的已绑定方案。': [
    '多个用户组同时生效时采用最高优先级方案。',
    'The highest-priority plan applies across multiple groups.',
  ],
  '用户属于多个用户组时，采用优先级最高的已绑定方案。': [
    '多个用户组同时生效时采用最高优先级方案。',
    'The highest-priority plan applies across multiple groups.',
  ],
  '开启后公开注册必须提交一个有效邀请码。': [
    '开启后，注册必须使用有效邀请码。',
    'When enabled, registration requires a valid invitation code.',
  ],
  '开启后，公开注册必须提交一个有效邀请码。': [
    '开启后，注册必须使用有效邀请码。',
    'When enabled, registration requires a valid invitation code.',
  ],
  '完整邀请码通过右上角消息中心投递给接收方。': [
    '邀请码通过消息中心发送。',
    'Invitation codes are sent through Messages.',
  ],
  '用户将继承所选用户组对应的权限与配额允许不选择任何用户组。': [
    '用户继承所选用户组的权限和配额。',
    'The user inherits permissions and quotas from selected groups.',
  ],
  '用户将继承所选用户组对应的权限与配额。允许不选择任何用户组。': [
    '用户继承所选用户组的权限和配额。',
    'The user inherits permissions and quotas from selected groups.',
  ],
  '保存后该用户的全部现有登录会话会立即失效。': [
    '保存后，该用户需要重新登录。',
    'The user must sign in again after saving.',
  ],
  '完整链接仅在生成后提供请及时保存。': [
    '链接仅在本次生成结果中显示。',
    'The full link is shown only in this result.',
  ],
  '完整链接仅在生成后提供，请及时保存。': [
    '链接仅在本次生成结果中显示。',
    'The full link is shown only in this result.',
  ],
  '已生成新的访问密码请及时保存。': [
    '新密码仅在本次结果中显示。',
    'The new password is shown only in this result.',
  ],
  '已生成新的访问密码，请及时保存。': [
    '新密码仅在本次结果中显示。',
    'The new password is shown only in this result.',
  ],
  配置已保存原链接保持不变: [
    '配置已保存，链接未变。',
    'Settings saved. The link is unchanged.',
  ],
  '配置已保存，原链接保持不变': [
    '配置已保存，链接未变。',
    'Settings saved. The link is unchanged.',
  ],
  在分享页显示我的用户名和头像: [
    '在分享页显示用户名和头像',
    'Show my name and avatar on the share page',
  ],
  可选填写分享内容说明: ['选填分享说明', 'Optional share description'],
  '可选，填写分享内容说明': ['选填分享说明', 'Optional share description'],
  此分享需要密码: ['需要访问密码', 'Password required'],
  '输入分享者提供的密码后查看和下载内容。': [
    '输入访问密码后可查看和下载内容。',
    'Enter the password to view and download the content.',
  ],
  '如果浏览器没有自动下载请点击下方按钮重试。': [
    '未自动下载时，可再次下载。',
    'If the download did not start, try again.',
  ],
  '如果浏览器没有自动下载，请点击下方按钮重试。': [
    '未自动下载时，可再次下载。',
    'If the download did not start, try again.',
  ],
  该格式不支持预览请下载后查看: [
    '该格式无法预览，请下载后查看。',
    'This format cannot be previewed. Download the file to view it.',
  ],
  '该格式不支持预览，请下载后查看': [
    '该格式无法预览，请下载后查看。',
    'This format cannot be previewed. Download the file to view it.',
  ],
  '当前身份没有对应权限或页面地址不存在。': [
    '当前身份无法访问此页面。',
    'Your current identity cannot access this page.',
  ],
  '当前身份没有对应权限，或页面地址不存在。': [
    '当前身份无法访问此页面。',
    'Your current identity cannot access this page.',
  ],
  无法访问此页面: ['无法访问此页面', 'Page unavailable'],
  无法打开分享: ['无法打开分享', 'Share unavailable'],

  文件列表加载失败: ['文件列表加载失败', 'Could not load files'],
  分享列表加载失败: ['分享列表加载失败', 'Could not load shares'],
  直链列表加载失败: ['直链列表加载失败', 'Could not load direct links'],
  实时概览加载失败: ['概览加载失败', 'Could not load the overview'],
  用户列表加载失败: ['用户列表加载失败', 'Could not load users'],
  权限与配额加载失败: [
    '权限与配额加载失败',
    'Could not load permissions and quotas',
  ],
  邀请码配置加载失败: [
    '邀请码配置加载失败',
    'Could not load invitation settings',
  ],
  审查数据加载失败: ['审查数据加载失败', 'Could not load review data'],
  系统配置加载失败: ['系统配置加载失败', 'Could not load settings'],
  消息加载失败: ['消息加载失败', 'Could not load messages'],
  上传失败: ['上传失败', 'Upload failed'],
  下载失败: ['下载失败', 'Download failed'],
  删除失败: ['删除失败', 'Delete failed'],
  保存失败: ['保存失败', 'Save failed'],
  批量操作失败: ['操作失败', 'Operation failed'],
  创建分享失败: ['分享生成失败', 'Could not create the share'],
  创建直链失败: ['直链生成失败', 'Could not create the direct link'],
  创建文件夹失败: ['文件夹创建失败', 'Could not create the folder'],
  保存配置失败: ['配置保存失败', 'Could not save settings'],
  审核操作失败: ['审核操作失败', 'Review action failed'],
  上传完成: ['上传完成', 'Upload complete'],
  删除完成: ['删除完成', 'Delete complete'],
  文件夹已创建: ['文件夹已创建', 'Folder created'],
  分享已生成: ['分享已生成', 'Share created'],
  直链已生成: ['直链已生成', 'Direct link created'],
  配置已保存: ['配置已保存', 'Settings saved'],
  已复制: ['已复制', 'Copied'],
  密码已复制: ['密码已复制', 'Password copied'],
  审核已通过: ['审核已通过', 'Approved'],
  审核已驳回: ['审核已驳回', 'Rejected'],
  邀请码已作废: ['邀请码已作废', 'Invitation code revoked'],
  用户已删除: ['用户已删除', 'User deleted'],
  用户已启用: ['用户已启用', 'User enabled'],
  用户已禁用: ['用户已禁用', 'User disabled'],
  用户组已新增: ['用户组已新增', 'User group added'],
  用户组已更新: ['用户组已更新', 'User group updated'],
  用户组已删除: ['用户组已删除', 'User group deleted'],
  用户组成员已更新: ['用户组成员已更新', 'Group members updated'],
  用户组归属已更新: ['用户组归属已更新', 'User groups updated'],
  用户组权限已保存: ['用户组权限已保存', 'Group permissions saved'],
  配额方案已删除: ['配额方案已删除', 'Quota plan deleted'],
  配额方案已新增: ['配额方案已新增', 'Quota plan added'],
  配额方案已更新: ['配额方案已更新', 'Quota plan updated'],
  系统配置已保存并实时生效: ['系统配置已保存', 'Settings saved'],
  站点图标已上传并实时生效: ['站点图标已更新', 'Site icon updated'],
  已恢复默认站点图标: ['已恢复默认图标', 'Default icon restored'],
  分享已删除: ['分享已删除', 'Share deleted'],
  分享已启用: ['分享已启用', 'Share enabled'],
  分享已禁用: ['分享已禁用', 'Share disabled'],
  直链已删除: ['直链已删除', 'Direct link deleted'],
  直链已启用: ['直链已启用', 'Direct link enabled'],
  直链已禁用: ['直链已禁用', 'Direct link disabled'],
  暂无内容: ['暂无内容', 'No messages'],
  暂无文件审查记录: ['暂无文件审查记录', 'No file reviews'],
  暂无自定义分享说明审查记录: ['暂无分享审查记录', 'No share reviews'],
  暂无系统审计记录: ['暂无系统审计记录', 'No audit records'],
  ' 次': [' 次', ' downloads'],
  '· 安全文件分享': [' · 文件分享', ' · Secure file sharing'],
  '· 文件下载': [' · 文件下载', ' · File download'],
  '· 文件与资源协作平台': [' · 文件协作平台', ' · File collaboration'],
  上传用户: ['上传用户', 'Uploaded by'],
  下载任务未返回有效地址: ['下载地址无效', 'The download address is invalid'],
  '下载失败，请稍后重试': ['下载失败', 'Download failed'],
  下载已开始: ['下载已开始', 'Download started'],
  下载文件: ['下载文件', 'Download file'],
  '下载文件.zip': ['下载文件.zip', 'download.zip'],
  两次输入的密码不一致: ['两次输入的密码不一致', 'The passwords do not match'],
  个: ['个', ''],
  个账户: ['个账户', ' accounts'],
  '仅未被任何用户组使用的非系统方案可以删除。': [
    '只能删除未被用户组使用的非系统方案。',
    'Only unused non-system plans can be deleted.',
  ],
  作废失败: ['作废失败', 'Revoke failed'],
  使用小写字母数字和下划线并以字母开头: [
    '使用小写字母、数字和下划线，并以字母开头。',
    'Use lowercase letters, numbers, and underscores. Start with a letter.',
  ],
  '使用小写字母、数字和下划线，并以字母开头': [
    '使用小写字母、数字和下划线，并以字母开头。',
    'Use lowercase letters, numbers, and underscores. Start with a letter.',
  ],
  '例如 project_member': ['例如 project_member', 'For example, project_member'],
  '例如 standard_user': ['例如 standard_user', 'For example, standard_user'],
  保存用户组权限失败: [
    '用户组权限保存失败',
    'Could not save group permissions',
  ],
  保存用户组配额失败: ['用户组配额保存失败', 'Could not save the group quota'],
  保存配额方案失败: ['配额方案保存失败', 'Could not save the quota plan'],
  再次输入新密码: ['再次输入新密码', 'Enter the new password again'],
  分享不存在或暂时无法访问: [
    '分享不存在或无法访问',
    'The share does not exist or is unavailable',
  ],
  分享密码错误: ['分享密码错误', 'Incorrect share password'],
  分享已失效: ['分享已失效', 'This share has expired'],
  分享已过期: ['分享已过期', 'Share expired'],
  分享已被封禁: ['分享已被封禁', 'Share blocked'],
  '分享链接将立即失效且无法恢复，原文件不会被删除。': [
    '分享将立即失效且无法恢复。原文件不会删除。',
    'The share will stop working and cannot be restored. Files are kept.',
  ],
  创建用户: ['创建用户', 'Created by'],
  删除用户失败: ['用户删除失败', 'Could not delete the user'],
  删除配额方案失败: ['配额方案删除失败', 'Could not delete the quota plan'],
  动作: ['动作', 'Action'],
  '名称须为 2 至 32 位小写字母、数字或下划线，并以字母开头': [
    '名称为 2 至 32 位小写字母、数字或下划线，并以字母开头。',
    'Use 2–32 lowercase letters, numbers, or underscores. Start with a letter.',
  ],
  '启用后该用户可以重新登录。': [
    '启用后，用户可以重新登录。',
    'The user can sign in again after being enabled.',
  ],
  图标上传失败: ['图标上传失败', 'Could not upload the icon'],
  复制密码: ['复制密码', 'Copy password'],
  复制直链: ['复制直链', 'Copy direct link'],
  复制链接: ['复制链接', 'Copy link'],
  字母: ['字母', 'letters'],
  实时概览: ['实时概览', 'Overview'],
  审查与审计: ['审查与审计', 'Review and audit'],
  密码已重设该用户的现有登录已失效: [
    '密码已重设，用户需要重新登录。',
    'Password reset. The user must sign in again.',
  ],
  '密码已重设，该用户的现有登录已失效': [
    '密码已重设，用户需要重新登录。',
    'Password reset. The user must sign in again.',
  ],
  密码至少需要8个字符: [
    '密码至少需要 8 个字符',
    'Password must contain at least 8 characters',
  ],
  '密码至少需要 8 个字符': [
    '密码至少需要 8 个字符',
    'Password must contain at least 8 characters',
  ],
  已关闭邀请码注册要求: [
    '注册不再需要邀请码',
    'Invitation codes are no longer required',
  ],
  已开启邀请码注册: ['注册现在需要邀请码', 'Invitation codes are now required'],
  恢复默认图标失败: ['默认图标恢复失败', 'Could not restore the default icon'],
  或: ['或', 'or'],
  搜索用户名: ['搜索用户名', 'Search usernames'],
  '支持 SVG、PNG、JPEG、WebP，最大 2MB。': [
    '支持 SVG、PNG、JPEG 和 WebP，最大 2 MB。',
    'SVG, PNG, JPEG, or WebP. Maximum size: 2 MB.',
  ],
  数字: ['数字', 'numbers'],
  '文件夹内的全部内容、相关分享和直链也会一并删除，且无法恢复。': [
    '文件夹内容及相关分享和直链会一并删除，且无法恢复。',
    'Folder contents and related links will be deleted permanently.',
  ],
  文件夹名称: ['文件夹名称', 'Folder name'],
  新增用户组失败: ['用户组新增失败', 'Could not add the user group'],
  删除用户组失败: ['用户组删除失败', 'Could not delete the user group'],
  配置用户组成员失败: ['用户组成员配置失败', 'Could not update group members'],
  新增配额方案: ['新增配额方案', 'Add quota plan'],
  方案名称须为2至32位小写字母数字或下划线: [
    '方案名称为 2 至 32 位小写字母、数字或下划线。',
    'Use 2–32 lowercase letters, numbers, or underscores.',
  ],
  '方案名称须为 2 至 32 位小写字母、数字或下划线': [
    '方案名称为 2 至 32 位小写字母、数字或下划线。',
    'Use 2–32 lowercase letters, numbers, or underscores.',
  ],
  旧记录不可恢复: ['原值不可恢复', 'Original value unavailable'],
  当前文件夹为空: ['当前文件夹为空', 'This folder is empty'],
  审核状态: ['审核状态', 'Review'],
  暂无分享: ['暂无分享', 'No shares'],
  暂无直链: ['暂无直链', 'No direct links'],
  当前用户组未授予预览权限: [
    '当前用户组未授予预览权限',
    'Your user group does not allow previews',
  ],
  请填写驳回原因: ['请填写驳回原因', 'Enter a rejection reason'],
  请输入新名称: ['请输入新名称', 'Enter a new name'],
  重命名完成: ['重命名完成', 'Renamed'],
  重命名失败: ['重命名失败', 'Could not rename the item'],
  更新用户状态失败: ['用户状态更新失败', 'Could not update user status'],
  更新用户组失败: ['用户组更新失败', 'Could not update user groups'],
  有效分享数量: ['有效分享数量', 'Active shares'],
  有效直链数量: ['有效直链数量', 'Active direct links'],
  权限与配额: ['权限与配额', 'Permissions and quotas'],
  查看分享: ['查看分享', 'Open share'],
  次: ['次', ''],
  注册策略更新失败: [
    '注册策略更新失败',
    'Could not update registration settings',
  ],
  消息清空失败: ['消息清空失败', 'Could not clear messages'],
  消息删除失败: ['消息删除失败', 'Could not delete message'],
  消息状态更新失败: ['消息状态更新失败', 'Could not update message status'],
  用户管理: ['用户管理', 'User management'],
  直链下载: ['直链下载', 'Direct download'],
  直链仅支持单个文件: [
    '直链仅支持单个文件',
    'Direct links support one file only',
  ],
  '直链将立即失效且无法恢复，原文件不会被删除。': [
    '直链将立即失效且无法恢复。原文件不会删除。',
    'The direct link will stop working and cannot be restored. The file is kept.',
  ],
  '禁用后该用户将立即退出登录，但文件和分享数据会保留。': [
    '禁用后，用户会退出登录，文件和分享仍会保留。',
    'The user will be signed out. Files and shares are kept.',
  ],
  系统消息: ['系统消息', 'System message'],
  系统配置: ['系统配置', 'System settings'],
  '该用户的文件、分享、直链和登录会话将一并删除，此操作不可恢复。': [
    '该用户的文件、分享和直链会一并删除，且无法恢复。',
    'The user and all files and links will be deleted permanently.',
  ],
  说明该用户组的用途: ['填写用户组用途', 'Describe this user group'],
  请先选择要删除的内容: ['请选择要删除的内容', 'Select content to delete'],
  请至少选择一项内容: ['请至少选择一项', 'Select at least one item'],
  请输入分享密码: ['请输入分享密码', 'Enter a share password'],
  请输入文件夹名称: ['请输入文件夹名称', 'Enter a folder name'],
  请输入站点名称: ['请输入站点名称', 'Enter a site name'],
  请输入绝对路径: ['请输入绝对路径', 'Enter an absolute path'],
  请输入驳回原因: ['请输入驳回原因', 'Enter a rejection reason'],
  请选择发放对象: ['请选择发放对象', 'Select a recipient'],
  请选择配额方案: ['请选择配额方案', 'Select a quota plan'],
  '输入新密码（至少 8 个字符）': [
    '输入新密码（至少 8 个字符）',
    'Enter a new password (at least 8 characters)',
  ],
  选择发放对象: ['选择发放对象', 'Select a recipient'],
  选择方案: ['选择方案', 'Select a plan'],
  选择用户组: ['选择用户组', 'Select user groups'],
  邀请码和分享码都必须至少包含字母或数字: [
    '邀请码和分享码必须包含字母或数字。',
    'Invitation and share codes must include letters or numbers.',
  ],
  邀请码生成失败: ['邀请码生成失败', 'Could not generate invitation codes'],
  邮件附件请下载原文件后查看: [
    '邮件附件需下载后查看',
    'Download email attachments to view them',
  ],
  重设密码失败: ['密码重设失败', 'Could not reset the password'],
  驳回审核: ['驳回审核', 'Reject review'],
  '（系统）': ['（系统）', ' (system)'],
  配额配置已保存: ['配额配置已保存', 'Quota settings saved'],
  邀请码已生成并发送: [
    '邀请码已生成并发送',
    'Invitation codes generated and sent',
  ],
  编辑配额方案: ['编辑配额方案', 'Edit quota plan'],
  删除配额方案: ['删除配额方案', 'Delete quota plan'],
  删除用户: ['删除用户', 'Delete user'],
  修改用户组: ['修改用户组', 'Change user groups'],
  编辑用户组: ['编辑用户组', 'Edit user group'],
  删除用户组: ['删除用户组', 'Delete user group'],
  删除直链: ['删除直链', 'Delete direct links'],
  删除分享: ['删除分享', 'Delete shares'],
  删除内容: ['删除内容', 'Delete items'],
  已选择: ['已选择', 'Selected'],
  共: ['共', 'Total'],
  项: ['项', 'items'],
  约: ['约', 'Around'],
  用户组管理: ['用户组管理', 'User group management'],
  系统用户组: ['系统用户组', 'System group'],
  暂无成员: ['暂无成员', 'No members'],
  配置人员: ['配置人员', 'Manage members'],
  选择人员: ['选择人员', 'Select members'],
  '分别管理站点用户和用户组。': [
    '分别管理站点用户和用户组。',
    'Manage users and user groups separately.',
  ],
  '新增、编辑、删除用户组，并配置组内人员。': [
    '新增、编辑、删除用户组，并配置组内人员。',
    'Add, edit, or delete groups and manage their members.',
  ],
  '选择需要加入此用户组的人员，系统超级管理员不会被变更。': [
    '选择需要加入此用户组的人员，系统超级管理员不会被变更。',
    'Select group members. The system super administrator is not changed.',
  ],
  '删除后无法恢复。': ['删除后无法恢复。', 'This cannot be undone.'],
  删除后该组内的: [
    '删除后，该组内的',
    'Deleting this group will remove it from',
  ],
  '名用户将失去此用户组提供的权限与配额。': [
    '名用户将失去此用户组提供的权限与配额。',
    'users, who will lose its permissions and quota.',
  ],
  '（系统超级管理员）': ['（系统超级管理员）', ' (system super administrator)'],
  已上传: ['已上传', 'Uploaded'],
  上传成功: ['上传成功', 'Uploaded'],
  邀请码格式不正确: [
    '邀请码格式不正确',
    'The invitation code format is invalid',
  ],
  上传任务: ['上传任务', 'Uploads'],
  展开: ['展开', 'Expand'],
  收起: ['收起', 'Collapse'],
  等待重新选择文件: [
    '等待重新选择原文件',
    'Select the original file to continue',
  ],
  正在校验文件: ['正在校验文件', 'Checking file'],
  等待上传: ['等待上传', 'Waiting'],
  正在上传: ['正在上传', 'Uploading'],
  已暂停: ['已暂停', 'Paused'],
  正在合并分片: ['正在合并分片', 'Finalizing'],
  已取消: ['已取消', 'Canceled'],
  上传任务加载失败: ['上传任务加载失败', 'Could not load upload tasks'],
  暂停上传失败: ['暂停上传失败', 'Could not pause the upload'],
  取消上传失败: ['取消上传失败', 'Could not cancel the upload'],
  继续上传失败: ['继续上传失败', 'Could not resume the upload'],
  '服务中断，请继续上传': [
    '服务曾中断，请继续上传。',
    'The service was interrupted. Resume the upload.',
  ],
  请选择原始上传文件: ['请选择原始上传文件', 'Select the original upload file'],
  所选文件与上传任务不匹配: [
    '所选文件与上传任务不匹配',
    'The selected file does not match this upload',
  ],
  暂停: ['暂停', 'Pause'],
  选择文件: ['选择文件', 'Select file'],
  继续: ['继续', 'Resume'],
  清除: ['清除', 'Clear'],
  分片上传: ['分片上传', 'Chunked uploads'],
  '分片应小于反向代理允许的请求体大小。默认 8M。': [
    '分片应小于反向代理允许的请求体大小，默认 8M。',
    'Keep chunks below the reverse proxy request-body limit. Default: 8 MB.',
  ],
  测试验证: ['测试验证', 'Test'],
  分片大小: ['分片大小', 'Chunk size'],
  分片大小验证通过: ['分片大小验证通过', 'Chunk size test passed'],
  分片大小验证失败: ['分片大小验证失败', 'Chunk size test failed'],
  单任务并发数: ['单任务并发数', 'Chunks per task'],
  单用户任务并发数: ['单用户任务并发数', 'Tasks per user'],
  '单任务并发数控制一个文件同时上传的分片数，单用户任务并发数控制同时上传的文件数。':
    [
      '单任务并发数控制一个文件同时上传的分片数；单用户任务并发数控制同时上传的文件数。',
      'Chunks per task controls parallel chunks for one file. Tasks per user controls parallel file uploads.',
    ],
  折叠: ['折叠', 'Collapse'],
  展开上传任务: ['展开上传任务', 'Expand uploads'],
  上移: ['上移', 'Move up'],
  下移: ['下移', 'Move down'],
  读取上传任务失败: ['读取上传任务失败', 'Could not refresh the upload task'],
  删除上传任务失败: ['删除上传任务失败', 'Could not delete the upload task'],
  调整上传队列失败: ['调整上传队列失败', 'Could not reorder the upload queue'],
  回收站: ['回收站', 'Trash'],
  回收期限: ['回收期限', 'Retention period'],
  天: ['天', 'days'],
  '到期内容将自动永久删除，默认保留 30 天。': [
    '到期内容将自动永久删除，默认保留 30 天。',
    'Expired items are permanently deleted automatically. Default: 30 days.',
  ],
  '所选内容将移入回收站，可在回收期限内恢复。': [
    '所选内容将移入回收站，可在回收期限内恢复。',
    'Selected items will move to Trash and can be restored during the retention period.',
  ],
  已移入回收站: ['已移入回收站', 'Moved to Trash'],
  回收站加载失败: ['回收站加载失败', 'Could not load Trash'],
  '回收站内容将在期限到期后自动永久删除。': [
    '回收站内容将在期限到期后自动永久删除。',
    'Trash items are permanently deleted when the retention period expires.',
  ],
  回收站最多为您保留: [
    '回收站最多为您保留',
    'Trash items are retained for up to',
  ],
  '，到期前您可以还原或提前删除。': [
    '，到期前您可以还原或提前删除。',
    ' days. You can restore or permanently delete them before expiration.',
  ],
  删除时间: ['删除时间', 'Deleted'],
  到期时间: ['到期时间', 'Expires'],
  恢复: ['恢复', 'Restore'],
  恢复完成: ['恢复完成', 'Item restored'],
  恢复失败: ['恢复失败', 'Could not restore the item'],
  永久删除: ['永久删除', 'Delete permanently'],
  '永久删除后无法恢复。': [
    '永久删除后无法恢复。',
    'This item cannot be restored after permanent deletion.',
  ],
  永久删除完成: ['永久删除完成', 'Item permanently deleted'],
  永久删除失败: ['永久删除失败', 'Could not permanently delete the item'],
  清空回收站: ['清空回收站', 'Empty Trash'],
  '回收站中的全部内容将被永久删除且无法恢复。': [
    '回收站中的全部内容将被永久删除且无法恢复。',
    'Everything in Trash will be permanently deleted and cannot be restored.',
  ],
  回收站已清空: ['回收站已清空', 'Trash emptied'],
  清空回收站失败: ['清空回收站失败', 'Could not empty Trash'],
  回收站为空: ['回收站为空', 'Trash is empty'],
  文件名: ['文件名', 'File name'],
  用户名: ['用户名', 'Username'],
  搜索审核内容: ['搜索审核内容', 'Search reviews'],
  搜索范围: ['搜索范围', 'Search fields'],
  搜索: ['搜索', 'Search'],
  未通过: ['未通过', 'Rejected'],
  文件已删除: ['文件已删除', 'File deleted'],
  已拉黑: ['已拉黑', 'Blocked'],
  文件审核加载失败: ['文件审核加载失败', 'Could not load file reviews'],
  分享审核加载失败: ['分享审核加载失败', 'Could not load share reviews'],
  审计日志加载失败: ['审计日志加载失败', 'Could not load audit logs'],
  请选择审核项目: ['请选择审核项目', 'Select items to review'],
  请输入审核意见: ['请输入审核意见', 'Enter review comments'],
  审核已提交: ['审核已提交', 'Review submitted'],
  请选择可下载文件: ['请选择可下载文件', 'Select downloadable files'],
  '审核文件.zip': ['审核文件.zip', 'review-files.zip'],
  审核回收站加载失败: ['审核回收站加载失败', 'Could not load moderation Trash'],
  上传者: ['上传者', 'Uploader'],
  上传时间: ['上传时间', 'Uploaded'],
  分享者: ['分享者', 'Owner'],
  分享时间: ['分享时间', 'Shared'],
  审核: ['审核', 'Review'],
  '审核所有用户上传的文件和分享内容。': [
    '审核所有用户上传的文件和分享内容。',
    'Review files and shares from every user.',
  ],
  暂无文件审核记录: ['暂无文件审核记录', 'No file reviews'],
  暂无分享审核记录: ['暂无分享审核记录', 'No share reviews'],
  文件审核: ['文件审核', 'File review'],
  分享审核: ['分享审核', 'Share review'],
  不通过: ['不通过', 'Reject'],
  审核意见: ['审核意见', 'Review comments'],
  审核操作: ['审核操作', 'Actions'],
  删除文件: ['删除文件', 'Delete file'],
  删除链接: ['删除链接', 'Delete link'],
  拉黑文件: ['拉黑文件', 'Block file'],
  封禁链接: ['封禁链接', 'Block link'],
  分享预览: ['分享预览', 'Share preview'],
  审核回收站: ['审核回收站', 'Moderation Trash'],
  '这里只允许永久删除，不支持恢复。': [
    '这里只允许永久删除，不支持恢复。',
    'Items can only be permanently deleted here and cannot be restored.',
  ],
  管理员限制恢复: ['管理员限制恢复', 'Restore blocked by administrator'],
};

export default function uiText(source: string): string {
  const entry = copy[source];
  if (!entry) return source;
  let language = 'zh-CN';
  try {
    language = window.localStorage.getItem('xph-lang') || language;
  } catch {
    // 无本地存储时使用中文。
  }
  return language === 'en-US' ? entry[1] : entry[0];
}

export function uiServerText(source: string): string {
  const translated = uiText(source);
  let language = 'zh-CN';
  try {
    language = window.localStorage.getItem('xph-lang') || language;
  } catch {
    // 无本地存储时使用中文。
  }
  if (language !== 'en-US' || translated !== source) return translated;
  if (!/[\u3400-\u9fff]/.test(source)) return source;
  if (source.includes('权限') || source.includes('仅系统超级管理员')) {
    return 'You do not have permission to perform this action.';
  }
  if (source.includes('不存在') || source.includes('已失效')) {
    return 'The requested item is unavailable.';
  }
  if (source.includes('已达到') || source.includes('超过')) {
    return 'The configured limit has been reached.';
  }
  if (source.includes('密码')) return 'The password is invalid.';
  if (
    source.includes('无效') ||
    source.includes('不合法') ||
    source.includes('请选择') ||
    source.includes('请输入')
  ) {
    return 'Check the submitted information and try again.';
  }
  return 'The request could not be completed.';
}
