// 中文文案即键，值为对应英文。
// 中文文案需要调整时写成 [中文, 英文]；未登记的内容保持原文，
// 动态的文件名、用户名和服务端消息不会被改写。
type CopyEntry = string | readonly [zhCN: string, enUS: string];

const copy: Record<string, CopyEntry> = {
  中文: '中文',
  文件: 'Files',
  文件夹: 'Folder',
  分享: 'Shares',
  直链: 'Direct links',
  用户: 'User',
  用户组: 'User group',
  系统: 'System',
  名称: 'Name',
  大小: 'Size',
  类型: 'Type',
  状态: 'Status',
  时间: 'Time',
  操作: 'Actions',
  操作者: 'Actor',
  对象: 'Target',
  格式: 'Format',
  说明: 'Description',
  密码: 'Password',
  '密码：': 'Password: ',
  有效期: 'Expiration',
  有效期至: 'Expires',
  创建时间: 'Created',
  更新时间: 'Updated',
  提交时间: 'Submitted',
  生成时间: 'Generated',
  '来源 IP': 'Source IP',
  保存: 'Save',
  保存配置: ['保存', 'Save'],
  取消: 'Cancel',
  完成: 'Done',
  创建: 'Create',
  生成: 'Generate',
  新增: 'Add',
  编辑: 'Edit',
  配置: 'Configure',
  删除: 'Delete',
  删除消息: 'Delete message',
  启用: 'Enable',
  禁用: 'Disable',
  作废: 'Revoke',
  通过: 'Approve',
  驳回: 'Reject',
  预览: 'Preview',
  下载: 'Download',
  上传: 'Upload',
  复制: 'Copy',
  打开: 'Open',
  刷新数据: ['刷新', 'Refresh'],
  返回首页: 'Back to home',
  返回登录: 'Back to login',
  重新下载: 'Download again',
  正在检查直链状态: ['正在检查直链状态…', 'Checking direct link…'],
  无法打开直链: 'Direct link unavailable',
  直链已过期: 'Direct link expired',
  直链已被封禁: 'Direct link blocked',
  该直链已过期: 'This direct link has expired',
  该直链已被管理员封禁: 'This direct link was blocked by an administrator',
  上传或替换: ['上传图标', 'Upload icon'],
  恢复默认: 'Restore default',
  新建文件夹: 'New folder',
  新增方案: 'Add plan',
  新增用户组: 'Add user group',
  重设密码: 'Reset password',
  '保存后该用户的全部现有登录会话会立即失效，动态令牌绑定也会清除，用户可在下次登录后重新绑定。': 'Saving invalidates all current sessions and clears the authenticator binding so the user can set it up again after signing in.',
  重命名: 'Rename',
  生成分享: 'Create share',
  生成直链: 'Create direct link',
  配置分享: 'Configure share',
  配置直链: 'Configure direct link',
  配置权限: 'Configure permissions',
  生成邀请码: 'Generate codes',
  发放邀请码: 'Issue invitation codes',
  确认驳回: 'Reject',
  全部已读: 'Mark all as read',
  全部消息: 'All messages',
  清空: 'Clear',
  条: 'messages',
  条未读: 'unread',
  '确认清空全部消息？': 'Clear all messages?',
  '清空后消息将从你的列表中移除。': 'All messages will be removed from your list.',
  切换语言: 'Change language',
  打开消息中心: 'Open messages',
  打开导航菜单: 'Open navigation',
  关闭导航菜单: 'Close navigation',
  展开导航菜单: 'Expand navigation',
  收起导航菜单: 'Collapse navigation',
  站点图标: 'Site icon',
  自定义首页: 'Custom homepage',
  启用自定义首页: 'Enable custom homepage',
  当前站点图标: 'Current site icon',
  全部文件: 'All files',
  文件总数: 'Files',
  用户总数: 'Users',
  有效分享: 'Active shares',
  有效直链: 'Active direct links',
  服务状态: 'Service status',
  分享消耗: ['分享用量', 'Share usage'],
  累计下载: 'Total downloads',
  累计流量: 'Total traffic',
  'API 服务': 'API service',
  数据库连接: 'Database',
  文件存储: 'File storage',
  正常: 'Operational',
  响应正常: ['运行正常', 'Operational'],
  更新于: 'Updated at',
  已用: 'Used',
  '/ 可用': '/ available',
  '/ 总量': '/ total',
  不可用: 'Unavailable',
  未能读取宿主磁盘信息: 'Host disk info unavailable',
  文件分享: 'Shared files',
  文件下载: 'File download',
  文件预览: 'File preview',
  当前资源: 'Selected item',
  分享内容: 'Shared content',
  直链内容: 'Linked file',
  分享链接: 'Share link',
  直链地址: 'Direct link',
  访问密码: 'Access password',
  自定义密码: 'Custom password',
  说明格式: 'Description format',
  分享页说明: ['分享说明', 'Share description'],
  分享说明: 'Share description',
  分享说明预览: 'Description preview',
  下载次数: 'Downloads',
  下载次数限制: 'Download limit',
  下载流量: 'Traffic',
  下载流量限制: 'Traffic limit',
  无密码: 'No password',
  不限: 'Unlimited',
  不限制: ['不限', 'Unlimited'],
  永久: 'Never',
  永久有效: 'Never expires',
  长期有效: 'No expiration',
  '1 天': '1 day',
  '7 天': '7 days',
  '30 天': '30 days',
  '从现在起 1 天': ['1 天', '1 day from now'],
  '从现在起 7 天': ['7 天', '7 days from now'],
  '从现在起 30 天': ['30 天', '30 days from now'],
  保持当前有效期: 'Keep current expiration',
  保持当前: 'Keep current',
  重新随机: ['重新生成', 'Generate new'],
  随机: ['随机生成', 'Random'],
  自定义: 'Custom',
  由: 'Shared by',
  到期: 'expires',
  已下载: 'Downloaded',
  已用流量: 'Traffic used',
  正在准备下载: 'Preparing download',
  空文件夹: ['文件夹为空', 'This folder is empty'],
  文件审查: 'File review',
  分享审查: 'Share review',
  系统审计: 'System audit',
  待审核: 'Pending',
  已通过: 'Approved',
  已驳回: 'Rejected',
  已停用: 'Disabled',
  已过期: 'Expired',
  生效中: 'Active',
  已禁用: 'Disabled',
  可使用: 'Available',
  已使用: 'Used',
  已作废: 'Revoked',
  系统超级管理员: 'Super administrator',
  所属用户组: 'User groups',
  用户组名称: 'Group name',
  配额方案: 'Quota plans',
  用户组配额: 'Group quotas',
  权限配置: 'Permissions',
  已授予权限: 'Granted permissions',
  未授予权限: 'No permissions granted',
  存储空间: 'Storage',
  单文件: 'Per file',
  单文件大小: 'File size',
  每日上传: 'Daily upload',
  每日上传流量: 'Daily upload traffic',
  每日上传次数: 'Daily uploads',
  每日下载: 'Daily download',
  每日下载流量: 'Daily download traffic',
  每日下载次数: 'Daily downloads',
  每日次数: 'Daily count',
  '分享 / 直链': 'Shares / direct links',
  优先级: 'Priority',
  注册策略: 'Registration',
  注册需要邀请码: 'Require an invitation code',
  邀请码: 'Invitation code',
  发放对象: 'Recipient',
  发放给用户: 'Send to user',
  发放给用户组: 'Send to user group',
  使用人: 'Used by',
  方案名称: 'Plan name',
  方案用途: 'Purpose',
  位数: 'Length',
  区分大小写: 'Case-sensitive',
  包含字母: 'Include letters',
  包含数字: 'Include numbers',
  内容审核: 'Content review',
  上传文件需要先审核: ['上传文件需要审核', 'Review uploaded files'],
  自定义分享说明需要先审核: ['自定义分享说明需要审核', 'Review custom share descriptions'],
  下载策略: 'Download settings',
  文件夹打包位置: ['文件夹打包方式', 'Folder packaging'],
  分享页文件交付: ['分享下载方式', 'Share delivery'],
  '后端校验并打包 ZIP': ['后端打包 ZIP', 'Package ZIP on the server'],
  前端逐文件打包: ['前端打包 ZIP', 'Package ZIP in the browser'],
  '前端读取 Blob 流': ['浏览器接收文件流', 'Receive as a browser blob'],
  一次性临时链接: ['临时下载链接', 'Temporary download link'],
  站点信息: 'Site',
  站点名称: 'Site name',
  存储路径: 'Storage path',
  随机码: 'Random codes',
  分享码: 'Share codes',
  取件码: 'Pickup code',
  取件: 'Retrieve',
  输入取件码: 'Enter pickup code',
  请输入取件码: 'Enter the pickup code',
  输入取件码后获取文件: 'Enter a pickup code to retrieve files.',
  '当前系统配置取件码：永久有效': 'Current pickup code lifetime: never expires',
  '当前允许使用的用户组：': 'Currently allowed user groups: ',
  '强制使用的用户组：': 'Required user groups: ',
  无: 'None',
  取件码生成后: 'Pickup codes are valid for',
  内有效: 'after creation.',
  取件码无效或已过期: 'The pickup code is invalid or expired.',
  '取件码仅在生成后提供，请及时保存。': 'Save this pickup code now.',
  分享方式: 'Share method',
  链接: 'Link',
  有效期上限: 'Maximum lifetime',
  系统上限: 'System maximum',
  秒: 'seconds',
  '1 小时': '1 hour',
  小时: 'hours',
  '填写 0 表示允许永久有效': 'Enter 0 to allow no expiration.',
  '系统取件码已用尽，请联系系统管理员处理！': 'Pickup codes are exhausted. Contact the system administrator.',
  取件页面: 'Pickup page',
  取件码有效期: 'Pickup code lifetime',
  '取件码有效期由系统设置决定，创建后不可修改': 'The pickup code lifetime follows the system settings and cannot be changed.',
  登录动态令牌: 'Login authenticator token',
  启用登录动态令牌: 'Enable login authenticator tokens',
  前往配置用户组权限: 'Configure user group permissions',
  用户配置: 'User settings',
  安全配置: 'Security',
  返回安全配置: 'Back to security',
  动态令牌: 'Authenticator token',
  配置动态令牌: 'Set up authenticator token',
  重新配置: 'Set up again',
  去配置: 'Set up now',
  已配置: 'Configured',
  未配置: 'Not configured',
  确认配置: 'Confirm setup',
  动态令牌二维码: 'Authenticator QR code',
  验证登录动态令牌: 'Verify authenticator token',
  '6 位动态令牌': '6-digit authenticator token',
  '请输入 6 位动态令牌': 'Enter the 6-digit authenticator token',
  验证并登录: 'Verify and sign in',
  返回账号登录: 'Back to password sign-in',
  请配置登录动态令牌: 'Set up your authenticator token',
  '打开验证器应用，输入当前显示的 6 位动态令牌。': 'Open your authenticator app and enter the current 6-digit token.',
  '请使用验证器应用扫描二维码，或手动复制下方链接。完成后输入应用显示的 6 位动态令牌以确认绑定。': 'Scan the QR code with an authenticator app, or copy the link below. Then enter the current 6-digit token to confirm.',
  '使用验证器应用保护账号登录。': 'Protect sign-in with an authenticator app.',
  '系统暂未启用登录动态令牌。': 'Login authenticator tokens are disabled system-wide.',
  '当前用户组没有使用登录动态令牌的权限。': 'Your user group cannot use login authenticator tokens.',
  '管理员已要求你的用户组使用登录动态令牌。你本次仍可继续使用，但下一次登录将强制验证，请务必现在完成配置。': 'Your administrator requires an authenticator token for this user group. This sign-in is allowed once; set it up now because it will be required next time.',
  安全配置加载失败: 'Could not load security settings',
  生成动态令牌失败: 'Could not create authenticator setup',
  动态令牌配置成功: 'Authenticator token configured',
  动态令牌校验失败: 'Authenticator token verification failed',
  动态令牌验证失败: 'Authenticator token verification failed',
  动态令牌无效或已过期: 'The authenticator token is invalid or expired',
  '账号必须先配置登录动态令牌，请联系系统管理员': 'This account must set up an authenticator token before signing in. Contact the system administrator.',
  '登录动态令牌策略已变更，请重新登录': 'The authenticator policy changed. Sign in again.',
  读取动态令牌配置失败: 'Could not load authenticator settings',
  没有配置动态令牌权限: 'You cannot configure an authenticator token',

  '在此粘贴完整的 HTML 内容': 'Paste the complete HTML here',
  '从 HTML 文件填充': 'Fill from HTML file',
  保存填写内容: 'Save HTML',
  'HTML 文件已读取，请确认内容后保存': 'HTML loaded. Review it, then save.',
  'HTML 文件读取失败': 'Could not read the HTML file',
  '请输入自定义首页 HTML': 'Enter custom homepage HTML',
  自定义首页内容加载失败: 'Could not load the custom homepage',
  自定义首页已保存并实时生效: 'Custom homepage saved',
  首页保存失败: 'Could not save the homepage',
  '自定义首页只接受 HTML 文本': 'The custom homepage accepts HTML text only',
  '首页 HTML 不能为空': 'Homepage HTML cannot be empty',

  '管理你的文件和文件夹。': ['查看和管理文件。', 'View and manage files.'],
  '查看你已经生成的文件和文件夹分享。': ['查看已生成的分享。', 'View generated shares.'],
  '查看你已经生成的下载直链及使用情况。': ['查看已生成的直链和使用量。', 'View direct links and usage.'],
  '掌握站点资源、分享和服务运行状态。': ['查看站点资源和服务状态。', 'View site resources and service status.'],
  '权限和配额均直接配置到用户组，用户只继承所属用户组的设置。': [
    '权限和配额由用户组决定。',
    'Permissions and quotas are assigned through user groups.',
  ],
  '调整站点基础信息、存储位置和全局下载行为。': ['配置站点、存储和下载方式。', 'Configure the site, storage, and downloads.'],
  '用于页面标题和产品标识。': ['显示在页面标题和站点标识中。', 'Shown in the page title and site identity.'],
  '必须填写服务器上的绝对路径。': ['填写服务器绝对路径。', 'Enter an absolute server path.'],
  '保存后仅影响新生成的邀请码和随机分享码，已有内容保持不变。': [
    '配置仅用于新生成的随机码。',
    'Changes apply only to newly generated codes.',
  ],
  '仅影响保存配置后新上传的文件和新提交的自定义分享说明。': [
    '配置仅用于之后提交的内容。',
    'Changes apply only to content submitted afterward.',
  ],
  '前端打包适合小型目录，后端打包对大目录更稳定；临时链接可交给浏览器直接下载。': [
    '选择文件夹打包和分享下载的处理位置。',
    'Choose where folder packaging and share downloads are handled.',
  ],
  '修改文件存储路径后，新上传和后续下载会立即使用新目录，请确认运行账户拥有读写权限。': [
    '修改后，新上传和下载会使用新路径。运行账户必须具有读写权限。',
    'New uploads and downloads use the new path. The service account needs read and write access.',
  ],
  '空值表示不限，0 表示禁止使用对应资源。': ['留空表示不限，0 表示禁用。', 'Leave blank for unlimited. Enter 0 to disable.'],
  '用户属于多个用户组时，采用优先级最高的已绑定方案。': [
    '多个用户组同时生效时采用最高优先级方案。',
    'The highest-priority plan applies across multiple groups.',
  ],
  '开启后，公开注册必须提交一个有效邀请码。': [
    '开启后，注册必须使用有效邀请码。',
    'When enabled, registration requires a valid invitation code.',
  ],
  '完整邀请码通过右上角消息中心投递给接收方。': ['邀请码通过消息中心发送。', 'Invitation codes are sent through Messages.'],
  '用户将继承所选用户组对应的权限与配额。允许不选择任何用户组。': [
    '用户继承所选用户组的权限和配额。',
    'The user inherits permissions and quotas from selected groups.',
  ],
  '完整链接仅在生成后提供，请及时保存。': ['链接仅在本次生成结果中显示。', 'The full link is shown only in this result.'],
  '已生成新的访问密码，请及时保存。': ['新密码仅在本次结果中显示。', 'The new password is shown only in this result.'],
  '配置已保存，原链接保持不变': ['配置已保存，链接未变。', 'Settings saved. The link is unchanged.'],
  在分享页显示我的用户名和头像: ['在分享页显示用户名和头像', 'Show my name and avatar on the share page'],
  '可选，填写分享内容说明': ['选填分享说明', 'Optional share description'],
  此分享需要密码: ['需要访问密码', 'Password required'],
  '输入分享者提供的密码后查看和下载内容。': [
    '输入访问密码后可查看和下载内容。',
    'Enter the password to view and download the content.',
  ],
  '该格式不支持预览，请下载后查看': [
    '该格式无法预览，请下载后查看。',
    'This format cannot be previewed. Download the file to view it.',
  ],
  '当前身份没有对应权限，或页面地址不存在。': ['当前身份无法访问此页面。', 'Your current identity cannot access this page.'],
  无法访问此页面: 'Page unavailable',
  无法打开分享: 'Share unavailable',

  文件列表加载失败: 'Could not load files',
  分享列表加载失败: 'Could not load shares',
  直链列表加载失败: 'Could not load direct links',
  实时概览加载失败: ['概览加载失败', 'Could not load the overview'],
  用户列表加载失败: 'Could not load users',
  权限与配额加载失败: 'Could not load permissions and quotas',
  邀请码配置加载失败: 'Could not load invitation settings',
  审查数据加载失败: 'Could not load review data',
  系统配置加载失败: 'Could not load settings',
  消息加载失败: 'Could not load messages',
  上传失败: 'Upload failed',
  下载失败: 'Download failed',
  删除失败: 'Delete failed',
  保存失败: 'Save failed',
  批量操作失败: ['操作失败', 'Operation failed'],
  创建分享失败: ['分享生成失败', 'Could not create the share'],
  创建直链失败: ['直链生成失败', 'Could not create the direct link'],
  创建文件夹失败: ['文件夹创建失败', 'Could not create the folder'],
  保存配置失败: ['配置保存失败', 'Could not save settings'],
  审核操作失败: 'Review action failed',
  上传完成: 'Upload complete',
  删除完成: 'Delete complete',
  文件夹已创建: 'Folder created',
  分享已生成: 'Share created',
  直链已生成: 'Direct link created',
  配置已保存: 'Settings saved',
  已复制: 'Copied',
  密码已复制: 'Password copied',
  审核已通过: 'Approved',
  审核已驳回: 'Rejected',
  邀请码已作废: 'Invitation code revoked',
  用户已删除: 'User deleted',
  用户已启用: 'User enabled',
  用户已禁用: 'User disabled',
  用户组已新增: 'User group added',
  用户组已更新: 'User group updated',
  用户组已删除: 'User group deleted',
  用户组成员已更新: 'Group members updated',
  用户组归属已更新: 'User groups updated',
  用户组权限已保存: 'Group permissions saved',
  配额方案已删除: 'Quota plan deleted',
  配额方案已新增: 'Quota plan added',
  配额方案已更新: 'Quota plan updated',
  系统配置已保存并实时生效: ['系统配置已保存', 'Settings saved'],
  站点图标已上传并实时生效: ['站点图标已更新', 'Site icon updated'],
  已恢复默认首页行为: ['已恢复登录页跳转', 'Default homepage behavior restored'],
  已恢复默认站点图标: ['已恢复默认图标', 'Default icon restored'],
  分享已删除: 'Share deleted',
  分享已启用: 'Share enabled',
  分享已禁用: 'Share disabled',
  直链已删除: 'Direct link deleted',
  直链已启用: 'Direct link enabled',
  直链已禁用: 'Direct link disabled',
  暂无内容: 'No messages',
  暂无系统审计记录: 'No audit records',
  ' 次': ' downloads',
  '· 安全文件分享': [' · 文件分享', ' · Secure file sharing'],
  '· 文件下载': [' · 文件下载', ' · File download'],
  '· 文件与资源协作平台': [' · 文件协作平台', ' · File collaboration'],
  上传用户: 'Uploaded by',
  下载任务未返回有效地址: ['下载地址无效', 'The download address is invalid'],
  下载已开始: 'Download started',
  下载文件: 'Download file',
  '下载文件.zip': 'download.zip',
  两次输入的密码不一致: 'The passwords do not match',
  个: '',
  个账户: ' accounts',
  '仅未被任何用户组使用的非系统方案可以删除。': ['只能删除未被用户组使用的非系统方案。', 'Only unused non-system plans can be deleted.'],
  作废失败: 'Revoke failed',
  '使用小写字母、数字和下划线，并以字母开头': [
    '使用小写字母、数字和下划线，并以字母开头。',
    'Use lowercase letters, numbers, and underscores. Start with a letter.',
  ],
  '例如 project_member': 'For example, project_member',
  '例如 standard_user': 'For example, standard_user',
  保存用户组权限失败: ['用户组权限保存失败', 'Could not save group permissions'],
  保存用户组配额失败: ['用户组配额保存失败', 'Could not save the group quota'],
  保存配额方案失败: ['配额方案保存失败', 'Could not save the quota plan'],
  再次输入新密码: 'Enter the new password again',
  分享不存在或暂时无法访问: ['分享不存在或无法访问', 'The share does not exist or is unavailable'],
  分享密码错误: 'Incorrect share password',
  分享已失效: 'This share has expired',
  分享已过期: 'Share expired',
  分享已被封禁: 'Share blocked',
  '分享链接将立即失效且无法恢复，原文件不会被删除。': [
    '分享将立即失效且无法恢复。原文件不会删除。',
    'The share will stop working and cannot be restored. Files are kept.',
  ],
  创建用户: 'Created by',
  删除用户失败: ['用户删除失败', 'Could not delete the user'],
  删除配额方案失败: ['配额方案删除失败', 'Could not delete the quota plan'],
  动作: 'Action',
  '名称须为 2 至 32 位小写字母、数字或下划线，并以字母开头': [
    '名称为 2 至 32 位小写字母、数字或下划线，并以字母开头。',
    'Use 2–32 lowercase letters, numbers, or underscores. Start with a letter.',
  ],
  '启用后该用户可以重新登录。': ['启用后，用户可以重新登录。', 'The user can sign in again after being enabled.'],
  图标上传失败: 'Could not upload the icon',
  复制密码: 'Copy password',
  复制直链: 'Copy direct link',
  复制链接: 'Copy link',
  字母: 'letters',
  实时概览: 'Overview',
  审查与审计: 'Review and audit',
  '密码已重设，该用户的现有登录已失效': ['密码已重设，用户需要重新登录。', 'Password reset. The user must sign in again.'],
  '请勿超过 18 位': 'Please do not exceed 18 characters',
  '密码至少 8 位': 'Password must be at least 8 characters',
  '密码太简单，请混合使用字母、数字或符号': 'Password is too easy to guess. Mix letters, numbers, or symbols',
  '输入新密码（8-18 位，建议混合字母与数字）': 'Enter a new password (8-18 characters)',
  '安全通道已更新，请重试': 'Secure channel refreshed. Please try again',
  '安全通道不可用': 'Secure channel unavailable',
  '安全校验已过期，请重试': 'Security check expired. Please try again',
  '账号需为 3 至 18 位': 'Username must be 3-18 characters',
  '账号不能包含空白或控制字符': 'Username cannot contain spaces or control characters',
  '密码需为 8 至 18 位': 'Password must be 8-18 characters',
  '账号或密码不符合要求': 'Username or password does not meet the requirements',
  '账号与密码均不能超过 18 位': 'Username and password must not exceed 18 characters',
  '当前站点要求使用 HTTPS 登录，请改用 HTTPS 地址访问': 'This site requires HTTPS for sign-in. Please open the HTTPS address',
  已关闭邀请码注册要求: ['注册不再需要邀请码', 'Invitation codes are no longer required'],
  已开启邀请码注册: ['注册现在需要邀请码', 'Invitation codes are now required'],
  恢复默认图标失败: ['默认图标恢复失败', 'Could not restore the default icon'],
  恢复默认首页失败: ['默认首页恢复失败', 'Could not restore the default homepage'],
  '当前已启用自定义首页。': 'A custom homepage is active. ',
  '未配置时访问首页将跳转到登录页面。': 'Without one, the homepage redirects to sign in. ',
  或: 'or',
  搜索用户名: 'Search usernames',
  '支持 SVG、PNG、JPEG 和 WebP。': 'SVG, PNG, JPEG, or WebP.',
  '支持单个 HTML 文件，可包含内嵌 CSS 和 JavaScript。': 'A single HTML file with inline CSS and JavaScript is supported.',
  '建议为登录页 /login、取件码 /m 等设计对应入口！': 'Consider adding links to /login and the pickup page /m.',
  数字: 'numbers',
  文件夹名称: 'Folder name',
  新增用户组失败: ['用户组新增失败', 'Could not add the user group'],
  删除用户组失败: ['用户组删除失败', 'Could not delete the user group'],
  配置用户组成员失败: ['用户组成员配置失败', 'Could not update group members'],
  新增配额方案: 'Add quota plan',
  '方案名称须为 2 至 32 位小写字母、数字或下划线': [
    '方案名称为 2 至 32 位小写字母、数字或下划线。',
    'Use 2–32 lowercase letters, numbers, or underscores.',
  ],
  旧记录不可恢复: ['原值不可恢复', 'Original value unavailable'],
  当前文件夹为空: 'This folder is empty',
  审核状态: 'Review',
  暂无分享: 'No shares',
  暂无直链: 'No direct links',
  当前用户组未授予预览权限: 'Your user group does not allow previews',
  当前用户组未授予上传权限: 'Your user group does not allow uploads',
  请填写驳回原因: 'Enter a rejection reason',
  请输入新名称: 'Enter a new name',
  重命名完成: 'Renamed',
  重命名失败: 'Could not rename the item',
  更新用户状态失败: ['用户状态更新失败', 'Could not update user status'],
  更新用户组失败: ['用户组更新失败', 'Could not update user groups'],
  有效分享数量: 'Active shares',
  有效直链数量: 'Active direct links',
  权限与配额: 'Permissions and quotas',
  查看分享: 'Open share',
  次: '',
  注册策略更新失败: 'Could not update registration settings',
  消息清空失败: 'Could not clear messages',
  消息删除失败: 'Could not delete message',
  消息状态更新失败: 'Could not update message status',
  用户管理: 'User management',
  直链下载: 'Direct download',
  直链仅支持单个文件: 'Direct links support one file only',
  '直链将立即失效且无法恢复，原文件不会被删除。': [
    '直链将立即失效且无法恢复。原文件不会删除。',
    'The direct link will stop working and cannot be restored. The file is kept.',
  ],
  '禁用后该用户将立即退出登录，但文件和分享数据会保留。': [
    '禁用后，用户会退出登录，文件和分享仍会保留。',
    'The user will be signed out. Files and shares are kept.',
  ],
  系统消息: 'System message',
  系统配置: 'System settings',
  '该用户的文件、分享、直链和登录会话将一并删除，此操作不可恢复。': [
    '该用户的文件、分享和直链会一并删除，且无法恢复。',
    'The user and all files and links will be deleted permanently.',
  ],
  说明该用户组的用途: ['填写用户组用途', 'Describe this user group'],
  请先选择要删除的内容: ['请选择要删除的内容', 'Select content to delete'],
  请至少选择一项内容: ['请至少选择一项', 'Select at least one item'],
  请输入分享密码: 'Enter a share password',
  请输入文件夹名称: 'Enter a folder name',
  请输入站点名称: 'Enter a site name',
  请输入绝对路径: 'Enter an absolute path',
  请输入驳回原因: 'Enter a rejection reason',
  请选择发放对象: 'Select a recipient',
  请选择配额方案: 'Select a quota plan',
  选择发放对象: 'Select a recipient',
  选择方案: 'Select a plan',
  选择用户组: 'Select user groups',
  邀请码和分享码都必须至少包含字母或数字: [
    '邀请码和分享码必须包含字母或数字。',
    'Invitation and share codes must include letters or numbers.',
  ],
  邀请码生成失败: 'Could not generate invitation codes',
  重设密码失败: ['密码重设失败', 'Could not reset the password'],
  驳回审核: 'Reject review',
  '（系统）': ' (system)',
  配额配置已保存: 'Quota settings saved',
  邀请码已生成并发送: 'Invitation codes generated and sent',
  编辑配额方案: 'Edit quota plan',
  删除配额方案: 'Delete quota plan',
  删除用户: 'Delete user',
  修改用户组: 'Change user groups',
  编辑用户组: 'Edit user group',
  删除用户组: 'Delete user group',
  删除直链: 'Delete direct links',
  删除分享: 'Delete shares',
  删除内容: 'Delete items',
  已选择: 'Selected',
  共: 'Total',
  项: 'items',
  约: 'Around',
  用户组管理: 'User group management',
  系统用户组: 'System group',
  暂无成员: 'No members',
  配置人员: 'Manage members',
  选择人员: 'Select members',
  '分别管理站点用户和用户组。': 'Manage users and user groups separately.',
  '新增、编辑、删除用户组，并配置组内人员。': 'Add, edit, or delete groups and manage their members.',
  '选择需要加入此用户组的人员，系统超级管理员不会被变更。': 'Select group members. The system super administrator is not changed.',
  '删除后无法恢复。': 'This cannot be undone.',
  '删除后，该组内的': 'Deleting this group will remove it from',
  '名用户将失去此用户组提供的权限与配额。': 'users, who will lose its permissions and quota.',
  '（系统超级管理员）': ' (system super administrator)',
  已上传: 'Uploaded',
  上传成功: 'Uploaded',
  邀请码格式不正确: 'The invitation code format is invalid',
  上传任务: 'Uploads',
  处理同名文件: 'Resolve duplicate files',
  请先处理当前的同名文件: 'Resolve the current duplicate files first',
  检查同名文件失败: 'Failed to check for duplicate files',
  继续上传: 'Continue upload',
  取消本次上传: 'Cancel this upload',
  '以下文件与待上传目录中的现有文件同名，请分别选择处理方式。': 'These files conflict with existing files in the destination. Choose how to handle each one.',
  覆盖: 'Overwrite',
  跳过: 'Skip',
  自动重命名: 'Auto rename',
  冲突文件名: 'Conflicting file',
  待上传路径: 'Upload path',
  处理方式: 'Action',
  展开: 'Expand',
  收起: 'Collapse',
  等待重新选择文件: ['等待重新选择原文件', 'Select the original file to continue'],
  正在校验文件: 'Checking file',
  等待上传: 'Waiting',
  正在上传: 'Uploading',
  已暂停: 'Paused',
  正在合并分片: 'Finalizing',
  已取消: 'Canceled',
  上传任务加载失败: 'Could not load upload tasks',
  暂停上传失败: 'Could not pause the upload',
  取消上传失败: 'Could not cancel the upload',
  继续上传失败: 'Could not resume the upload',
  '服务中断，请继续上传': ['服务曾中断，请继续上传。', 'The service was interrupted. Resume the upload.'],
  请选择原始上传文件: 'Select the original upload file',
  所选文件与上传任务不匹配: 'The selected file does not match this upload',
  暂停: 'Pause',
  选择文件: 'Select file',
  继续: 'Resume',
  清除: 'Clear',
  分片上传: 'Chunked uploads',
  '分片应小于反向代理允许的请求体大小。默认 8M。': [
    '分片应小于反向代理允许的请求体大小，默认 8M。',
    'Keep chunks below the reverse proxy request-body limit. Default: 8 MB.',
  ],
  测试验证: 'Test',
  分片大小: 'Chunk size',
  分片大小验证通过: 'Chunk size test passed',
  分片大小验证失败: 'Chunk size test failed',
  单任务并发数: 'Chunks per task',
  单用户任务并发数: 'Tasks per user',
  '单任务并发数控制一个文件同时上传的分片数，单用户任务并发数控制同时上传的文件数。': [
    '单任务并发数控制一个文件同时上传的分片数；单用户任务并发数控制同时上传的文件数。',
    'Chunks per task controls parallel chunks for one file. Tasks per user controls parallel file uploads.',
  ],
  折叠: 'Collapse',
  展开上传任务: 'Expand uploads',
  上移: 'Move up',
  下移: 'Move down',
  读取上传任务失败: 'Could not refresh the upload task',
  删除上传任务失败: 'Could not delete the upload task',
  调整上传队列失败: 'Could not reorder the upload queue',
  回收站: 'Trash',
  回收期限: 'Retention period',
  天: 'days',
  '到期内容将自动永久删除，默认保留 30 天。': 'Expired items are permanently deleted automatically. Default: 30 days.',
  '所选内容将移入回收站，可在回收期限内恢复。': 'Selected items will move to Trash and can be restored during the retention period.',
  已移入回收站: 'Moved to Trash',
  回收站加载失败: 'Could not load Trash',
  回收站最多为您保留: 'Trash items are retained for up to',
  '，到期前您可以还原或提前删除。': ' days. You can restore or permanently delete them before expiration.',
  删除时间: 'Deleted',
  到期时间: 'Expires',
  恢复: 'Restore',
  恢复完成: 'Item restored',
  恢复失败: 'Could not restore the item',
  永久删除: 'Delete permanently',
  '永久删除后无法恢复。': 'This item cannot be restored after permanent deletion.',
  永久删除完成: 'Item permanently deleted',
  永久删除失败: 'Could not permanently delete the item',
  清空回收站: 'Empty Trash',
  '回收站中的全部内容将被永久删除且无法恢复。': 'Everything in Trash will be permanently deleted and cannot be restored.',
  回收站已清空: 'Trash emptied',
  清空回收站失败: 'Could not empty Trash',
  回收站为空: 'Trash is empty',
  文件名: 'File name',
  用户名: 'Username',
  搜索审核内容: 'Search reviews',
  搜索范围: 'Search fields',
  搜索: 'Search',
  未通过: 'Rejected',
  文件已删除: 'File deleted',
  已拉黑: 'Blocked',
  文件审核加载失败: 'Could not load file reviews',
  分享审核加载失败: 'Could not load share reviews',
  审计日志加载失败: 'Could not load audit logs',
  请选择审核项目: 'Select items to review',
  请输入审核意见: 'Enter review comments',
  审核已提交: 'Review submitted',
  请选择可下载文件: 'Select downloadable files',
  '审核文件.zip': 'review-files.zip',
  审核回收站加载失败: 'Could not load moderation Trash',
  上传者: 'Uploader',
  上传时间: 'Uploaded',
  分享者: 'Owner',
  分享时间: 'Shared',
  审核: 'Review',
  '审核所有用户上传的文件和分享内容。': 'Review files and shares from every user.',
  暂无文件审核记录: 'No file reviews',
  暂无分享审核记录: 'No share reviews',
  文件审核: 'File review',
  分享审核: 'Share review',
  不通过: 'Reject',
  审核意见: 'Review comments',
  审核操作: 'Actions',
  删除文件: 'Delete file',
  删除链接: 'Delete link',
  拉黑文件: 'Block file',
  封禁链接: 'Block link',
  分享预览: 'Share preview',
  审核回收站: 'Moderation Trash',
  '这里只允许永久删除，不支持恢复。': 'Items can only be permanently deleted here and cannot be restored.',
  管理员限制恢复: 'Restore blocked by administrator',
  用户已彻底删除: 'Permanently deleted by user',
  'SHA-256 校验码：': 'SHA-256: ',
  复制校验码: 'Copy checksum',
  '校验码可用于核对下载文件内容的完整性。': 'Use the checksum to verify the integrity of the downloaded file.',
  '文件已被管理员限制，无法覆盖': 'This file is restricted by an administrator and cannot be overwritten.',
  分享页交付方式: 'Share page delivery',
  本机中转: 'Relay via server',
  '302 直跳第三方': '302 redirect to storage',
  '选择 302 时，文件由浏览器直连存储后端下载：明文文件无需处理，浏览器一次跳转即可下载；加密文件先下发密钥信封，再由浏览器拉取密文并解密（服务器不承担流量）。预览与文件夹打包固定走本机中转。302 模式下实时解密开关不生效。': 'With 302, the browser fetches files directly from the storage backend: plain files need no extra step—one redirect starts the download; encrypted files receive a key envelope first, then the browser pulls the ciphertext and decrypts it (no server traffic). Preview and folder archives always use the relay. The realtime decryption switch has no effect in 302 mode.',
  服务器实时解密: 'Server-side realtime decryption',
  '开启后，本机中转交付的加密文件由服务器解密后输出明文；关闭后改由浏览器端解密（密钥实时非对称下发，仅 HTTPS 部署可用），"一次性临时链接"会自动降级为"前端读取 Blob 流"以保证可解密。直链始终由服务器解密，不受此开关影响。': 'When enabled, encrypted files delivered via relay are decrypted on the server. When disabled, decryption happens in the browser (asymmetric key delivery, HTTPS only) and "one-time temporary link" degrades to "Blob stream" to stay decryptable. Direct links are always decrypted on the server.',
  存储加密: 'Storage encryption',
  '存储空间包含回收站中的文件（彻底删除或保留期到期后释放）；每日上传流量/次数按自然日（服务器本地时区）统计。每日下载流量/次数限制下载者（登录用户按账号，未登录访问按来源 IP 各自计算，使用「未登录访客」用户组绑定的配额）。': 'Storage quota includes files in the recycle bin (released after permanent deletion or retention expiry); daily upload traffic/count is measured per calendar day (server local time). Daily download limits apply to the downloader (signed-in accounts individually; unauthenticated visitors per source IP, using the quota bound to the "Guest" user group).',
  新文件加密存储: 'Encrypt new files',
  当前部署未配置加密密钥: 'No encryption key configured',
  '开启后新上传的文件使用 AES-256-GCM 分块加密存储（每个文件独立随机密钥，密钥经部署密钥包裹后保存在数据库）；关闭时新文件保持明文存储，历史文件不受影响。': 'New uploads are stored with chunked AES-256-GCM encryption (per-file random key wrapped by the deployment key). When disabled, new files stay plain; existing files are unaffected.',
  '当前部署未配置加密密钥（XPH_ENCRYPTION_KEYS），无法开启新文件加密。': 'This deployment has no encryption key (XPH_ENCRYPTION_KEYS), so new-file encryption cannot be enabled.',
  '该文件已加密存储': 'Stored with encryption',
  存储管理: 'Storage',
  本机存储: 'Local storage',
  '123 云盘': '123 Cloud Drive',
  默认: 'Default',
  未就绪: 'Not ready',
  已用容量: 'Used',
  新增存储后端: 'Add backend',
  编辑存储后端: 'Edit backend',
  '请输入名称': 'Please enter a name',
  '例如：云盘归档': 'e.g. Cloud archive',
  '存储根目录文件夹 ID': 'Root folder ID',
  '请输入文件夹 ID': 'Please enter the folder ID',
  '在 123 云盘中创建用于存放文件的文件夹，填入其数字 ID（根目录 0 不支持直链）。': 'Create a folder in 123 Cloud Drive for files and fill in its numeric ID (root 0 does not support direct links).',
  设为默认上传目标: 'Set as default upload target',
  '存储后端已保存并即时生效': 'Storage backend saved and applied immediately',
  '读取存储后端失败': 'Failed to load storage backends',
  '保存存储后端失败': 'Failed to save storage backend',
  '登记文件存储后端：新上传默认写入「默认」后端；停用后端不会删除已有文件，历史对象仍可正常读取。': 'Register storage backends: new uploads go to the default backend; disabling a backend never deletes existing files.',
  '123 云盘的 access_token 由服务端自动申请与续期（30 天有效），密钥不会下发到浏览器。': 'The 123 Cloud Drive access token is issued and renewed server-side (valid 30 days); secrets never reach the browser.',
  '当前部署未配置 123 云盘应用凭据（XPH_PAN123_CLIENT_ID / XPH_PAN123_CLIENT_SECRET），无法启用 123 云盘后端。': 'This deployment has no 123 Cloud Drive credentials (XPH_PAN123_CLIENT_ID / XPH_PAN123_CLIENT_SECRET), so the 123 backend cannot be enabled.',
  分享优先使用: 'Prefer for shares',
  直链优先使用: 'Prefer for direct links',
  自用下载流量: 'Self-use download traffic',
  直链流量: 'Direct-link traffic',
  '分享页与文件页下载经本机中转时，服务端从 123 取内容消耗哪份额度；是否走 302 由下方「交付方式」单独决定。': 'Which 123 quota the server consumes when proxying share/file-page downloads. Whether to use 302 is decided separately by "Delivery mode" below.',
  交付方式: 'Delivery mode',
  优先本机中转: 'Prefer server proxying',
  优先302连接: 'Prefer 302 direct link',
  '优先本机中转（默认）：由服务器转发，用户始终只访问本站地址。优先302连接：明文文件让浏览器直连 123（消耗直链流量），需站点交付策略为 302；选它会自动为 123 云盘开启直链空间（幂等）。加密文件与多分片对象仍走本机中转。': 'Prefer proxying (default): the server relays the bytes and users only ever access this site. Prefer 302: plaintext files make the browser fetch directly from 123 (consuming direct-link traffic); requires the site delivery mode to be 302 and automatically enables the 123 direct-link space (idempotent). Encrypted and multi-part objects are still proxied.',
  '站内直链 /d/ 始终经本机中转（对外只有一个固定地址、交付可用的明文）；此设置只决定服务端从 123 取内容时消耗哪份额度。选「直链流量」时会自动为 123 云盘开启直链空间（幂等，只开不关）。': 'The /d/ direct link always proxies through the server (one stable public URL, plaintext delivery). This setting only chooses which 123 quota the server consumes when fetching the content; choosing direct-link traffic automatically enables the direct-link space on 123 Cloud Drive (idempotent, never disabled).',
  自用与直链可在异常时互相切换: 'Switch between self-use and direct-link on failure',
  '开启（默认）：所选通道不可用时自动改用另一条通道，下载不中断。关闭：严格使用所选通道（上面两项的「优先」即「始终」），不可用时直接报错，不会消耗另一份额度——便于判断额度是否用完。': 'On (default): fall back to the other channel when the chosen one fails, so downloads never break. Off: strictly use the chosen channel (the two "prefer" options become "always"); failures are reported instead of consuming the other quota, making quota exhaustion easy to spot.',
  启用直链鉴权: 'Enable direct-link auth',
  '需先在 123 云盘直链管理的「鉴权管理」中开启并配置同一密钥；开启后下载地址会带签名，防止直链被他人盗用。': 'First enable it in 123 Cloud Drive → Direct link → Auth settings and configure the same key. Signed download URLs prevent hotlinking.',
  鉴权密钥: 'Auth key',
  '只保存在服务端，不会回显；留空表示沿用已保存的密钥。': 'Stored server-side only and never echoed back; leave blank to keep the saved key.',
  '已保存（留空不修改）': 'Saved (leave blank to keep)',
  '粘贴 123 云盘「鉴权管理」中的密钥': 'Paste the key from 123 Cloud Drive auth settings',
  对象存储: 'Object storage',
  Endpoint: 'Endpoint',
  Bucket: 'Bucket',
  Region: 'Region',
  '请输入 Endpoint': 'Please enter the endpoint',
  '请输入 Bucket': 'Please enter the bucket',
  'S3 兼容服务地址，如 https://minio.example.com（不包含 bucket）。': 'S3-compatible endpoint, e.g. https://minio.example.com (without bucket).',
  对象键前缀: 'Object key prefix',
  '可选：与其它系统共用 bucket 时用于隔离目录。': 'Optional: isolate objects when sharing a bucket with other systems.',
  'Path-Style 寻址': 'Path-style addressing',
  'MinIO / Cloudflare R2 建议开启；AWS S3 新桶需关闭（virtual-hosted 寻址）。': 'Recommended for MinIO / Cloudflare R2; disable for new AWS S3 buckets (virtual-hosted).',
  '对象存储支持 S3 兼容协议（AWS S3 / MinIO / Cloudflare R2 / 阿里云 OSS / 腾讯云 COS），访问密钥只保存在部署 .env 中。': 'Object storage supports the S3-compatible protocol (AWS S3 / MinIO / R2 / OSS / COS); credentials stay in the deployment .env.',
  '当前部署未配置对象存储访问凭据（XPH_S3_ACCESS_KEY_ID / XPH_S3_SECRET_ACCESS_KEY），无法启用对象存储后端。': 'This deployment has no object storage credentials (XPH_S3_ACCESS_KEY_ID / XPH_S3_SECRET_ACCESS_KEY), so the S3 backend cannot be enabled.',
  // 维护任务：选项 → 扫描 → 按结果执行
  孤立文件: 'Orphaned objects',
  加密: 'Encrypt',
  解密: 'Decrypt',
  分片: 'Chunking',
  迁移: 'Migrate',
  扫描: 'Scan',
  执行: 'Apply',
  结果: 'Result',
  命中: 'Matched',
  查看结果: 'View result',
  清理: 'Clean up',
  扫描结果: 'Scan result',
  执行明细: 'Execution details',
  无引用残留: 'Unreferenced leftover',
  '对象 ID': 'Object ID',
  待处理: 'Pending',
  已跳过: 'Skipped',
  '找出没有被任何文件引用的残留数据；系统不会自动清理，确认清单后手动清理（会真正删除文件）。': 'Find leftover data that no file references. Nothing is cleaned up automatically — review the list and clean it manually (files are really deleted).',
  '把明文文件改成加密存储；先扫描出清单，确认后再执行。': 'Convert plaintext files to encrypted storage. Scan first, then confirm to apply.',
  '把加密文件改回明文存储；先扫描出清单，确认后再执行。': 'Convert encrypted files back to plaintext storage. Scan first, then confirm to apply.',
  '按指定大小重新切分文件；先扫描出不符合的文件，确认后再执行。': 'Re-chunk files to the given size. Scan for mismatching files first, then confirm to apply.',
  '把文件从原位置搬到新位置；搬完后删除原位置的文件。': 'Move files from the source to the destination; source objects are deleted after a successful move.',
  '扫描范围：全部后端': 'Scope: all backends',
  '原位置（留空＝其它全部）': 'Source (blank = all others)',
  新位置: 'Destination',
  开始扫描: 'Start scan',
  开始迁移: 'Start migration',
  '扫描完成：没有需要处理的对象': 'Scan finished: nothing to process',
  '扫描完成，命中': 'Scan finished, matched',
  '个对象，确认后可在下方执行': 'objects; confirm below to apply',
  扫描失败: 'Scan failed',
  '已按该扫描结果创建执行任务，正在后台执行': 'Execution task created from this scan result; running in the background',
  创建执行任务失败: 'Failed to create the execution task',
  '迁移任务已创建，正在后台执行': 'Migration task created; running in the background',
  创建迁移任务失败: 'Failed to create the migration task',
  '确认开始迁移？': 'Start migration?',
  '会把文件从原位置搬到新位置，搬移成功后删除原位置的对象。': 'Files are moved to the destination; source objects are deleted after each successful move.',
  '确认清理这些文件？': 'Clean up these files?',
  '确认执行？': 'Apply now?',
  '将物理删除清单中的对象，此操作不可恢复。': 'Objects in the list will be permanently deleted. This cannot be undone.',
  将按扫描出的清单处理: 'Apply to the scanned list:',
  个对象: 'objects',
  读取任务结果失败: 'Failed to load the task result',
  刷新: 'Refresh',
  重新分片: 'Re-chunk objects',
  '新上传分片大小（MiB）': 'Chunk size for new uploads (MiB)',
  '分片存储为强制项（不可关闭）：必须是 4MiB 的整数倍（4~1024），默认 64MiB。分片与加密兼容（分片边界与加密块对齐），已有对象可在「存储管理」用分片任务重写。': 'Chunked storage is mandatory (cannot be disabled): must be a multiple of 4MiB (4–1024), default 64MiB. Chunking is compatible with encryption (chunk boundaries align with encryption blocks); existing objects can be re-chunked from Storage.',
  '文件校验失败：内容与服务器记录不一致，请重试': 'Integrity check failed: content does not match the recorded checksum. Please retry.',
  '加密元数据无法解析，请刷新页面后重试': 'Failed to parse encryption metadata. Please refresh and retry.',
  '加密元数据不完整，请刷新页面后重试': 'Incomplete encryption metadata. Please refresh and retry.',
  '密文长度与元数据不符，文件可能不完整': 'Ciphertext length does not match metadata; the file may be incomplete.',
  '加密元数据的明文长度无效': 'Invalid plaintext length in encryption metadata.',
  MiB: 'MiB',
  维护任务: 'Maintenance tasks',
  迁移到后端: 'Migrate to backend',
  存量补加密: 'Encrypt existing files',
  清理孤儿对象: 'Purge orphan objects',
  选择目标后端: 'Select target backend',
  创建任务: 'Create task',
  排队中: 'Queued',
  执行中: 'Running',
  已完成: 'Completed',
  任务: 'Task',
  进度: 'Progress',
  '迁移：把对象搬到指定存储后端（搬移成功后删除旧对象）；补加密：把明文对象改为加密存储；清理孤儿：物理删除没有被任何资源引用的文件（唯一会真正删除文件的入口，请谨慎执行）。': 'Migrate: move objects to the selected backend (old objects removed after a successful move). Encrypt: convert plain objects to encrypted storage. Purge: permanently delete objects no longer referenced by any resource (the only path that physically deletes files — use with care).',
  '读取存储任务失败': 'Failed to load storage tasks',
  '创建存储任务失败': 'Failed to create storage task',
  '任务已创建，正在后台执行': 'Task created and running in the background',
  '没有需要处理的对象': 'No objects to process',
  '确认清理孤儿对象？': 'Purge orphan objects?',
  '将物理删除没有被任何资源引用的文件，此操作不可恢复（仅清理已登记为孤儿的对象）。': 'Files not referenced by any resource will be physically deleted. This cannot be undone (only objects already marked as orphaned are affected).',
  '该文件需要在浏览器端解密，请刷新页面后重试': 'This file is decrypted in the browser. Please refresh the page and try again.',
  '存储后端': 'Storage backend',
  '默认（跟随全局）': 'Default (global)',
  '切换用户组存储绑定': 'Change group storage backend',
  '该组成员的新上传将写入': 'New uploads from this group will be stored in',
  '存量文件会自动创建迁移任务搬到新存储，可在存储任务页查看进度。': 'Existing files will be migrated to the new storage by an automatic background task. Track its progress on the storage tasks page.',
  '确认切换': 'Confirm change',
  '存储绑定已切换，迁移任务已创建': 'Storage binding updated and the migration task has been created',
  '存储绑定已保存': 'Storage binding saved',
  '保存用户组存储绑定失败': 'Saving the group storage binding failed',
  '自动迁移任务创建失败，请在存储任务页手动发起迁移': 'The automatic migration task could not be created. Please start it manually on the storage tasks page.',
  '该文件需要在浏览器端解密，但当前环境不支持': 'This file is decrypted in the browser, which is not supported in this environment.',
  '失败': 'Failed',
  '复制失败': 'Copy failed',
  '移除自定义首页': 'Remove custom homepage',
  '将删除已保存的自定义首页内容，此操作不可撤销。': 'The saved custom homepage will be deleted. This cannot be undone.',
  '确认移除': 'Remove',
  '预览加载失败': 'Failed to load preview',
  '分享文件被封禁或正在审核': 'This shared file is blocked or under review',
  '请先填写分片大小': 'Please enter the upload chunk size first',
  '消息中心': 'Message center',
  '消息详情': 'Message details',
  '查看通知、系统消息和需要处理的内容。': 'View notifications, system messages and items that need attention.',
  '暂无消息正文': 'No message content',
  '关闭': 'Close',
  '标记为已读': 'Mark as read',
  '未读': 'Unread',
  '成员': 'Members',
  '已删除': 'Deleted',
  '提交': 'Submit',
  '取件码：': 'Pickup code: ',
  '分享链接：': 'Share link: ',
  '直链地址：': 'Direct link: ',
  '请先完善表单中的存储配置': 'Please complete the storage settings in the form first',
  '存储后端列表读取失败，请刷新重试': 'Failed to load the storage backend list. Please refresh and try again.',
  '没有需要保存的变更': 'There are no changes to save',
  '存储绑定决定该组成员新上传的落盘位置，切换会触发迁移任务。': 'The storage binding decides where new uploads of this group are stored; changing it triggers a migration task.',
  '存储用量': 'Storage usage',
  '请输入当前动态令牌': 'Enter your current 2FA code',
  '清理失效取件码': 'Release dead pickup codes',
  '已释放失效取件码': 'Released pickup codes',
  '没有需要清理的失效取件码': 'No dead pickup codes to release',
  '清理失效取件码失败': 'Failed to release pickup codes',
  '部分取件码已更换': 'Some pickup codes were rotated',
  '码已失效': 'Code released',
  '该取件码已失效并可被重新分配；重新启用该分享时会复用或换发新码。': 'This pickup code has been released and may be reallocated. Re-enabling the share reuses it or issues a new code.',
  '已恢复为': 'Restored as',
  '管理员限制删除': 'Deletion restricted',
  '回收站中的全部内容将被永久删除且无法恢复（管理员限制的文件会保留，需由管理员处理）。': 'Everything in the trash will be permanently deleted. Files restricted by an administrator are kept and must be handled by an administrator.',
  '取件码已更换': 'Pickup code rotated',
  '原取件码已被其它分享占用，已为你生成新的取件码，请重新告知取件人。': 'The previous pickup code was taken by another share, so a new code was issued. Please inform the recipient again.',
  '取件码默认有效期': 'Default pickup code lifetime',
  '允许永久有效的取件码（码空间有限，可在分享页「清理失效取件码」腾位置）': 'Allow permanent pickup codes (code space is finite; use "Release dead pickup codes" in the shares page to free slots)',
  '邀请码有效期（天，0 = 永久）': 'Invitation validity (days, 0 = never expires)',
  '0 表示永久': '0 means never expires',
  '单文件上限（GB）': 'Max file size (GB)',
  '全部分享': 'All shares',
  '一键释放失效取件码': 'Release dead pickup codes',
  '已释放': 'Released',
  '在途上传': 'In-progress uploads',
  '取消任务': 'Cancel task',
  '上传任务已取消': 'Upload task canceled',
  '改期': 'Change expiry',
  '解除封禁': 'Unblock',
  '取件码管理': 'Pickup codes',
  '所有者': 'Owner',
  '已封禁': 'Blocked',
  '搜索取件码 / 用户名 / 文件名': 'Search by code / username / file name',
  '读取在途上传失败': 'Failed to load in-progress uploads',
  '将取消该上传任务并清理已上传的分片': 'This cancels the upload task and clears its uploaded chunks',
  '进行中的上传任务会占用临时盘；用户放弃的任务可在此直接取消。': 'In-progress uploads occupy temporary disk; abandoned tasks can be canceled here.',
  '操作失败': 'Operation failed',
  '操作成功': 'Operation succeeded',
  '当前已配置动态令牌，请先输入当前显示的动态码': 'A 2FA secret is already configured. Enter the code currently shown in your authenticator first.',
  '到期内容将自动永久删除，默认保留 30 天。缩短保留期后，超出期限的内容会在下一次清理时立即彻底删除。': 'Expired items are purged automatically (30 days by default). If you shorten the retention period, items beyond it are purged at the next cleanup run.',
  '宿主磁盘': 'Host disk',
  '对象占用': 'Object usage',
  '所有交付（分享页、文件页、管理端审核）均由浏览器接收：取数、解密、合并与打包在前端完成，服务端只负责鉴权、发地址与计数。': 'All deliveries (share page, file page, admin review) are received by the browser: fetching, decryption, merging and packing happen client-side; the server only authenticates, issues addresses and counts usage.',
  分享取数方式: 'Share retrieval mode',
  '302 优先': 'Prefer 302',
  中转优先: 'Prefer proxying',
  '302 优先（默认）：浏览器逐片直连第三方存储逐片取数并自行解密合并，流量不过服务器（需存储后端启用直链）。中转优先：一律经由本机中转，由前端解密或服务器兜底解密。': 'Prefer 302 (default): the browser fetches each part straight from third-party storage and decrypts/merges locally, so traffic bypasses the server (requires direct links on the storage backend). Prefer proxying: everything goes through the server, decrypted in the browser or, as a fallback, by the server.',
  '302 不可用时自动降级中转': 'Fall back to proxying when 302 is unavailable',
  '开启后：302 不可用（存储后端未启用直链、或浏览器无法完成解密）时自动改走本机中转；关闭后直接提示下载失败（不展示内部原因）。': 'When on: if 302 is unavailable (no direct links on the storage backend, or the browser cannot decrypt), delivery automatically falls back to proxying. When off: downloads fail with a generic error (no internal details shown).',
  '优先本机中转（默认）：由服务器转发，用户始终只访问本站地址。优先302连接：浏览器逐片直连 123 取数（消耗直链流量）并自行解密合并，需站点取数方式为 302 优先；选它会自动为 123 云盘开启直链空间（幂等）。': 'Prefer proxying (default): the server relays the bytes and users only ever access this site. Prefer 302: the browser fetches each part directly from 123 (consuming direct-link traffic) and decrypts/merges locally; requires the share retrieval mode to be "Prefer 302". Selecting it automatically enables the 123 direct-link space (idempotent).',
  '允许跨用户秒传复用（关闭后仅复用自己已有的文件，更保护隐私）': 'Allow cross-user instant-upload reuse (when off, only your own existing files are reused, for better privacy)',
  "开启时按内容哈希全平台去重：任何用户知道文件的 SHA-256 与大小即可秒传他人的私有文件（省存储但可能越权读取）；关闭后只与自己已有的对象去重。": "When on, deduplication is global by content hash: anyone who knows a file's SHA-256 and size can instant-upload another user's private file (saves storage, but may allow reading others' private files). When off, deduplication only matches objects you already own.",
  已启用: 'Enabled',
  停用: 'Disable',
  刷新页面: 'Refresh page',
  页面出错了: 'Something went wrong',
  '该页面渲染失败，其它页面与后台功能不受影响；刷新即可重试。': 'This page failed to render. Other pages and background features are unaffected; refresh to retry.',
  没有可下载的文件: 'No downloadable files',
  '下载失败，请稍后重试': 'Download failed, please try again later',
};

function currentLanguage(): string {
  try {
    return window.localStorage.getItem('xph-lang') || 'zh-CN';
  } catch {
    // 无本地存储时使用中文。
    return 'zh-CN';
  }
}

export default function uiText(source: string): string {
  const entry = copy[source];
  if (entry === undefined) return source;
  const english = currentLanguage() === 'en-US';
  if (typeof entry === 'string') return english ? entry : source;
  return english ? entry[1] : entry[0];
}

export function uiServerText(source: string): string {
  const translated = uiText(source);
  if (currentLanguage() !== 'en-US' || translated !== source) return translated;
  if (!/[\u3400-\u9fff]/.test(source)) return source;
  if (source.includes('权限') || source.includes('仅系统超级管理员')) {
    return 'You do not have permission to perform this action.';
  }
  if (source.includes('不存在') || source.includes('已失效')) {
    return 'The requested item is unavailable.';
  }
  if (source.includes('已达到') || source.includes('超过')) {
    return 'The configured limit has been reached.';
  }
  if (source.includes('密码')) return 'The password is invalid.';
  if (
    source.includes('无效') ||
    source.includes('不合法') ||
    source.includes('请选择') ||
    source.includes('请输入')
  ) {
    return 'Check the submitted information and try again.';
  }
  return 'The request could not be completed.';
}
